### ISSUE TITLE
congrats!

### ISSUE THREAD

**Issue by aquynh** [avast-tl/retdec#1]
congrats on this amazing work! just added your projects to our website at http://www.capstone-engine.org/showcase.html

keep it up, cheers!

**Comment by s3rvac** [comment]
Thank you!

**Comment by taspeotis** [comment]
I would also like to say thank you for this project. I've used it via your website and the output is quite nice.

**Comment by don1001** [comment]
Any plans to add raw binary decompilation ? I have a simple home-made dissembler with file format parsing and procedure search I'd love to add decompilation just like in IDA. Some standalone retdec tool would be great where user specifies input file and architecture and gets in return "C" code with corresponding asm addresses in the comments.

**Comment by s3rvac** [comment]
@don1001 RetDec supports raw binary decompilation. For example, to decompile raw machine code (x86, little endian) in file named `FILE` into C source code, run e.g.

```
./decompile.sh FILE --mode raw --arch x86 --endian little --raw-entry-point ADDR --raw-section-vma ADDR
```

For more details, run `./decompile.sh --help` and read our [raw-machine-decompilation guide](http://localhost/decompilation-service/api/docs/guides.html#raw-decompilation-guide).
