### ISSUE TITLE
Fileinfo: potentially dangerous use of sizeof(string)

### ISSUE THREAD

**Issue by PeterMatula** [avast-tl/retdec#124]
In these two files:
- `ar-extractor/detection.cpp`
- `fileformat/file_format/macho/macho_format.cpp`

There is code like this:
```c
sizeof("!<arch>")
```

Sizeof returns the size of object in bytes, in this case including terminating `\0`. What is the expected value here? Is it not 7? In any case, use `std::strlen()` to find out the size of string. Make sure that code that uses the results is modified as well. For example here in `ar-extractor/detection.cpp` should probably be `arMagicSize + 1` in array definition:
```c
104	std::ifstream inputFile(path, std::ifstream::binary);
105	if (inputFile) {
106		char start[arMagicSize] = {};
107		inputFile.read(start, arMagicSize);
108
109		return startsWith(start, archMagic) || startsWith(start, thinMagic);
110	}
```

Search for, and fix, similar code elsewhere.

**Note:**
This was originally reported as a memory leak problem in `fileinfo`, but I was not able to reproduce it. Input binary was named `msvc.lib`, with sha256: `5f34536f98259022e84786632fee3ca40ace2ca1a2d3915ab68b6d0b1b64ae2c`.

Execution:
```
valgrind --track-origins=yes retdec-fileinfo msvc.lib
```

Output:
```
Conditional jump or move depends on uninitialised value(s)
   at 0x4C2C1B8: strlen (vg_replace_strmem.c:412)
   by 0x5963C30: std::basic_string<...>::basic_string(...) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20)
   by 0x657640: preprocessing::ar_extractorl::isArchive(std::string const&) (detection.cpp:113)
   by 0x5AA6A6: main (fileinfo.cpp:428)
 Uninitialised value was created by a stack allocation
   at 0x657476: basic_ios (basic_ios.h:456)
   by 0x657476: basic_ifstream (fstream:488)
   by 0x657476: preprocessing::ar_extractorl::isArchive(std::string const&) (detection.cpp:108)
```

If you are able to reproduce it, make sure it is fixed by the proposed code modifications.

**Comment by mbandzi** [comment]
fixed in master
