### ISSUE TITLE
Macho-extractor: support extraction of any object from fat Mach-O

### ISSUE THREAD

**Issue by PeterMatula** [avast-tl/retdec#125]
The original tool was created to extract archives from fat Mach-O archives. But it would be useful, if it could extract any object from fat Mach-O. E.g. binary, that is not an archive.

Maybe, this is all that needs to be done: 
```diff
---    valid = isStaticLibrary();
+++    valid = true; //isStaticLibrary();
```

But it needs to be checked before using it in master.

**Comment by mbandzi** [comment]
fixed in master
