### ISSUE TITLE
Fileinfo: VisualBasic header parsing + P-Code detection

### ISSUE THREAD

**Issue by PeterMatula** [avast-tl/retdec#138]
Visual Basic can be compiled into binary or P-Code - bytecode for VB virtual machines. Add VBHeader parsing and dumping to fileinfo. [Description](https://www.vb-decompiler.org/pcode_decompiling.htm).

How to do it:
- When Visual Basic is detected, look at EP where should be `push offset 0x????????`. VBHeader should be at this offset. Some of its records are pointers to other structures (e.g. `ProjectInfo`).
- Add detection of P-Code (`aNativeCode == 0`), tag the input as bytecode, warn users that decompiling this is not a good idea.

This might help: https://github.com/SekoiaLab/pe-tools

Also some pictures from IDA where these structures were defined and used:
![blacktsanalysis](https://user-images.githubusercontent.com/20342097/35625064-3e57b1fa-0691-11e8-9d03-ff182c19463e.png)
![dmmanalysis](https://user-images.githubusercontent.com/20342097/35625068-40879dd2-0691-11e8-9c44-1e6879f6b138.png)

**Comment by s3rvac** [comment]
I am closing the issue as it has been implemented in #440.
