### ISSUE TITLE
Better support for ELF core files

### ISSUE THREAD

**Issue by PeterMatula** [avast-tl/retdec#142]
[ELF core files](http://www.gabriel.urdhr.fr/2015/05/29/core-file/) are process dumps. Analyze how well can our tools deal with such files. Improve the tools if there are some problems. Example: [core.zip](https://github.com/avast-tl/retdec/files/1682096/core.zip).

**Comment by mbandzi** [comment]
Added in  [3461c6bb93b99684](https://github.com/avast-tl/retdec/commit/3461c6bb93b996842b32c73cf522fc8061f1d9eb). Tool `retdec-fileinfo` can now print information about note sections and segments, core file map, core auxiliary vector and other ELF notes related information.
