### ISSUE TITLE
Converting the complete environment from Bash to Python because of portability

### ISSUE THREAD

**Issue by 0xBEEEF** [avast-tl/retdec#147]
I wanted to ask if there are any plans to remove the bash completely from the project? In the presentation for the release of the project as open source, there was still talk of the need to switch to Python to make it more portable than before. 

![portable](https://user-images.githubusercontent.com/36008527/35754048-55c4c5b2-0862-11e8-9f0c-3816382914ac.JPG)

Unfortunately, I don't see any plans on the roadmap for this anymore. In my opinion, however, it would be quite desirable if Python could be used to depict the whole thing. This way you wouldn't have to do such a headstand under Windows to get the system up and running. The best way to do this is to simply run the program without external dependencies. That makes it entirely portable.

**Comment by PeterMatula** [comment]
I added it to the long term plan. We would like to do it, but there are quite a few more important goals.

**Comment by 0xBEEEF** [comment]
Thank you very much! Of course there are more important topics than this one, but I was just wondering why it was missing on the list. I'm closing the issue now! Thanks for the quick response!

**Comment by s3rvac** [comment]
I am re-opening this as we surely want to do it, although not right now.

**Comment by TheCodez** [comment]
I did some work towards converting all scripts to Python, which can be seen in my [Branch](https://github.com/TheCodez/retdec/tree/python).

It's still early work in progress. Apart from  `retdec-decompiler` and `retdec-signature-from-library-creator` every script is converted. Converted meaning they _compile_ and look reasonable like a python script. However some scripts still emplace some non portable bash commands, which should be replaced by their python equivalent.

This could be used as a starting point, so any feedback or help would be greatly appreciated.

**Comment by PeterMatula** [comment]
Done - everything is in `master`. We will do a new release with this in the next few days.

**Comment by 0xBEEEF** [comment]
That's great news! Thank you for your efforts.
