### ISSUE TITLE
hex rays decompiler internals

### ISSUE THREAD

**Issue by MerovingianByte** [avast-tl/retdec#149]
https://www.hex-rays.com/products/ida/support/ppt/recon2018.ppt

Ilfak Guilfanov presentation on hex rays' decompiler. Just thought I'd share it here since it could be useful for ideas or...something? Anyway, not expecting this "issue" to be left open, it's more of a heads up.

**Comment by s3rvac** [comment]
Thank you. One of us (@PeterMatula ) was actually at the conference and saw the talk :).

**Comment by MerovingianByte** [comment]
Also it might be a good time to spend a few thousand dollars on ida pro, they published the microcode:
https://www.hex-rays.com/products/ida/7.1/index.shtml
