### ISSUE TITLE
Fileinfo is slow on attached PE samples due to many symbols

### ISSUE THREAD

**Issue by PeterMatula** [avast-tl/retdec#161]
Why is it taking so much time? Can we do something about it?
- [C588759584B60FD97E891564F244DADA0338F18AD37DEB312BB4FB15D787D08B](https://www.virustotal.com/en/file/C588759584B60FD97E891564F244DADA0338F18AD37DEB312BB4FB15D787D08B/analysis/)
- [E825577E799AF7F82A926ED777FBB2C8F3132851FDD7A4B1C60ACECEF77972F0](https://www.virustotal.com/en/file/E825577E799AF7F82A926ED777FBB2C8F3132851FDD7A4B1C60ACECEF77972F0/analysis/)
- `94A39E7584B34D5AEFC9455869EBDBEEF3B5104AEF731E652A0FF88B698A1709`
- `627E6A128DB51D711798BB26816CC2CCEA7595B9486F1B4DF8A7C2C208966AD0`

**Comment by s3rvac** [comment]
Basic information about the attached files:
```
$ file *
627E6A128DB51D711798BB26816CC2CCEA7595B9486F1B4DF8A7C2C208966AD0: PE32+ executable (console) x86-64, for MS Windows
94A39E7584B34D5AEFC9455869EBDBEEF3B5104AEF731E652A0FF88B698A1709: PE32 executable (GUI) Intel 80386, for MS Windows
C588759584B60FD97E891564F244DADA0338F18AD37DEB312BB4FB15D787D08B: PE32+ executable (GUI) x86-64, for MS Windows
E825577E799AF7F82A926ED777FBB2C8F3132851FDD7A4B1C60ACECEF77972F0: PE32 executable (GUI) Intel 80386, for MS Windows
```
```
$ du -h *
91M     627E6A128DB51D711798BB26816CC2CCEA7595B9486F1B4DF8A7C2C208966AD0
90M     94A39E7584B34D5AEFC9455869EBDBEEF3B5104AEF731E652A0FF88B698A1709
90M     C588759584B60FD97E891564F244DADA0338F18AD37DEB312BB4FB15D787D08B
118M    E825577E799AF7F82A926ED777FBB2C8F3132851FDD7A4B1C60ACECEF77972F0
```
Running times of `retdec-fileinfo` on my PC (`Release` build, commit 60fdb6f717fc1fadf981f30b7f11e6efde67f805):
```
627E6A128DB51D711798BB26816CC2CCEA7595B9486F1B4DF8A7C2C208966AD0: 3.5s
94A39E7584B34D5AEFC9455869EBDBEEF3B5104AEF731E652A0FF88B698A1709: 3.7s
C588759584B60FD97E891564F244DADA0338F18AD37DEB312BB4FB15D787D08B: 3.4s
E825577E799AF7F82A926ED777FBB2C8F3132851FDD7A4B1C60ACECEF77972F0: 5.3s
```
Considering the size of the files, I think the running times are normal. Since there are no details in the description, I am closing this issue.
