### ISSUE TITLE
Online Doxygen?

### ISSUE THREAD

**Issue by Manouchehri** [avast-tl/retdec#20]
Would be nice if the generated documentation was automatically rebuilt and hosted online.

e.g. https://retdec.thaw.systems/doc/html/annotated.html

**Comment by s3rvac** [comment]
Yes, we definitely want to do that.

**Comment by PeterMatula** [comment]
TeamCity builds the documentation and creates an artifact that is referenced in our main `README.md`. Hopefully this will work ok.
