### ISSUE TITLE
Finish the new converter of LLVM IR into BIR

### ISSUE THREAD

**Issue by s3rvac** [avast-tl/retdec#211]
Currently, there are two converters of LLVM IR into BIR in `llvmir2hll` (see source code in `src/llvmir2hll/llvm/llvmir2bir_converters`):
* `orig` Original converter, which has been in the decompiler since its beginning.
* `new` A complete rewrite of the converter.

The used converter can be set via `--backend-llvmir2bir-converter` when running `retdec-decompiler.sh`. Currently, the default one is `orig`, because the new converter is not finished.

We should finish the converter. It has the following two main issues:
* It generates `goto` targets without labels (e.g. `goto xyz;` is generated, but there is no `xyz` label in the code).
* It generates more `goto` statements than the original converter.

A word of caution: Several people have already tried to finish the new converter, but none of them succeeded. It is not an easy task.

**Comment by PeterMatula** [comment]
The default LLVM IR to BIR converter was changed in e6f47cf6ae6bd3d79793b61364831fca74739bbf. This commit is already in `master`.
