### ISSUE TITLE
Temporary turned off test due to segmentation fault

### ISSUE THREAD

**Issue by mbandzi** [avast-tl/retdec#215]
Test `tools/fileinfo/bugs/1136` for MIPS is temporary turned off as it causes segmentation fault on Windows 10. Test can be turned on when currently used version of YARA is replaced with v3.7.0 or higher.

**Comment by PeterMatula** [comment]
New test name is `tools/fileinfo/bugs/elfio-segfault/`.
Test for sample `mips-elf-833b75712348c48d46ed822c1757515a`.

**Comment by PeterMatula** [comment]
YARA upgraded as requested in #218 in branch `yara-3.7.1`. Need to test this on Windows 10.

**Comment by PeterMatula** [comment]
Upgrade to YARA 3.7.1 indeed helped.
