### ISSUE TITLE
FilesystemPath.exists() stopped working

### ISSUE THREAD

**Issue by mbandzi** [avast-tl/retdec#216]
After changes in `FilesystemPath` function `exists` stopped working.
Other functions (`isFile`, `isDircetory`) work normally.

If this is fixed, uncomment unit tests in `tests/utils/binary_path_tests.cpp`.

**Comment by s3rvac** [comment]
Fixed in 3348489ca6d40d088dd26551777b0a57737421a0, including uncommenting of the two unit tests.
