### ISSUE TITLE
Upgrade YARA to newer version

### ISSUE THREAD

**Issue by mbandzi** [avast-tl/retdec#218]
Decompiler currently uses version based on v3.6.3 release.
New version fixes several bugs in ELF module (#215).

Note: in newer versions, keyword `entry_point_for_arch` is used instead of old `ep_for_arch` so Mach-O signatures in `support/yara_patterns/tools/macho` have to be fixed.

**Comment by s3rvac** [comment]
I am re-opening this issue as we still use YARA 3.6.3 in RetDec (the upgrade to YARA 3.7 is still in an unmerged branch). As both yaracpp and yaramod use YARA 3.8, we should also use YARA 3.8 in RetDec.
