### ISSUE TITLE
ci.appveyor.com error

### ISSUE THREAD

**Issue by Karaulov** [avast-tl/retdec#234]
https://ci.appveyor.com/project/avast-tl/retdec?branch=master

https://ci.appveyor.com/project/avast-tl/retdec/branch/master/artifacts is empty, please fix it for download latest build retrec.

**Comment by mbandzi** [comment]
I believe it will not be possible to use appVeyor artifacts this way due to their 1GB limit - size of Windows release build is almost 4GB.

**Comment by Karaulov** [comment]
In release section i found retdec-v3.0-windows-64b.zip with 256MB size, where you found 4GB ?

**Comment by Karaulov** [comment]
![wcope89 1](https://user-images.githubusercontent.com/6445336/36965287-44e189b8-206a-11e8-8e65-a8b5c9bd40c7.png)

**But if build passed without problem, impossible to save output data to artifacts or upload it to another server or github releases ?**
