### ISSUE TITLE
fileinfo emits non-printable characters for "Subject name" of a digital certificate

### ISSUE THREAD

**Issue by s3rvac** [avast-tl/retdec#253]
In the text mode, `fileinfo` emits non-printable characters for _Subject name_ of a digital certificate of the attached PE file.

## Input

Run
```
$ retdec-fileinfo --verbose FILE
```
where `FILE` is:
* [03EA764EAD2C27B0A98C48A18D4CC8E831F3D9A7BF62A471C2D57EF81183CF80](https://www.virustotal.com/intelligence/search/?query=03EA764EAD2C27B0A98C48A18D4CC8E831F3D9A7BF62A471C2D57EF81183CF80)

## Output

![non-printable-characters-pe-certificate](https://user-images.githubusercontent.com/5675953/37580221-d76e4554-2b42-11e8-9f01-4039e9120fcc.png)

The ordinal value of the two non-printable characters is 0 (i.e. they are null bytes).

## Expected output

```
Certificate #0
Subject name        : Microsoft Windows 20\x00\x00 Publisher
Subject organization: Microsoft Corporation
Subject             : /C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Copyright (c) 20\x00\x00 Microsoft Corp./CN=Microsoft Windows 20\x00\x00 Publisher
Issuer name         : Microsoft Windows Verification Intermediate PCA
```

That is, _Subject name_ should be properly escaped, just like _Subject_.

## Notes

* What is interesting is that in the JSON mode, the characters get properly escaped:
    ```
    $ retdec-fileinfo --verbose --json FILE
    ...
            "subject" :
            {
                "commonName" : "Microsoft Windows 20\\x00\\x00 Publisher",
                ...
            }
    ...
    ```
  There seems to be an inconsistency between the escaping in the text and JSON modes.

## Configuration

* Commit: a24aabbc0363b9a2097b9f91cdd90a15561b0423 (current `master`)
* 64b Arch Linux, GCC 7.3.0, Debug build of RetDec

**Comment by metthal** [comment]
Fixed in 0a70ec5787028f19bf72fbbf805f39c3ee194112.
