### ISSUE TITLE
A mistake when using fileinfo and bin2llvmir on linux (Kali) 

### ISSUE THREAD

**Issue by Joel-MalwareBenchmark** [avast-tl/retdec#277]
Hello
When I use the fileinfo on Windows 10 and linux .It appears a common missing.
![image](https://user-images.githubusercontent.com/33394474/38863362-ff563f8e-4269-11e8-83bd-8c92e80c95f6.png)
Check  it,please.The information I obtained have no functions.However, when i use a same cmd yesterday on win10,it could work correctly.
![image](https://user-images.githubusercontent.com/33394474/38863519-75dbccfa-426a-11e8-9b3c-7b4f17cb8cd5.png)
Next picture is today results when I using bin2llvmir on linux or windows10
![image](https://user-images.githubusercontent.com/33394474/38863345-eda3eb88-4269-11e8-9f71-bc2d6ba4ca2b.png)

**Comment by s3rvac** [comment]
Hi, could you please provide the following information?
* What version of RetDec do you use? Our [initial release](https://github.com/avast-tl/retdec/releases/tag/v3.0) or have you built RetDec by yourself from the current `master`?
* Attach the input file that you are trying to decompile.
* What command did you use to decompile that file + on which operating system?
* Attach a complete output from the decompilation (what it printed to the console).
* Attach all files that the decompilation produced (`.c`, `.bc`, `.dsm`, `.json`, etc).
* What output did you expect to get? That is, write e.g. _I expected the output to contain ABC, but it contains DEF_.

**Comment by Joel-MalwareBenchmark** [comment]
Hello,I have solve this quesion. However,I have some new questions about it.
I used the retdec version of released on windows10  x64 and kali x64. However the IR I obtained is different, If I just want to obtain the IR from binary, and It could recognize correctly some stacic function(such as printf,etc..).How could I used command ,and what platform should I use(gcc 5.3? gcc 7.3? kali x64 ?Windows10x64 release? Ubuntu 32?)

**Comment by s3rvac** [comment]
I am sorry but I do not understand what you are asking. In order for us to help you, you will need to provide the following information:
* Attach the input file that you are trying to decompile.
* What command did you use to decompile that file + on which operating system?
* Attach a complete output from the decompilation (what it printed to the console).
* Attach all files that the decompilation produced (`.c`, `.bc`, `.dsm`, `.json`, etc).
* What output did you expect to get? That is, write e.g. _I expected the output to contain ABC, but it contains DEF_.

**Comment by Joel-MalwareBenchmark** [comment]
[4.zip](https://github.com/avast-tl/retdec/files/1930538/4.zip)

Hello, This is I com
