### ISSUE TITLE
Web Interface?

### ISSUE THREAD

**Issue by agnosticlines** [avast-tl/retdec#28]
Hi folks,

Just wanted to say amazing work, been using this project for a few years now for CTF/VR work.

The fact you guys have open sourced such an awesome product is really good to see. Excited to finally have a mature open source decompiler. Hopefully someone can give the other paid solutions a run for their money.

My question is a little odd, the UI you guys use on retdec.com will that be open sourced? I've talked to my team about it and they're very interested in running it on one of our large servers and letting researchers connect to it and upload samples. The retdec.com UI was slick as hell. Was just wondering if you have any intention of open sourcing that?

Cheers :-)

**Comment by s3rvac** [comment]
Hi! Thank you for your kind words. We are very glad that you find the decompiler useful.

Currently, we do not plan to open source the web interface or the online decompilation service. Maybe in the future ;-).
