### ISSUE TITLE
Our unpacker is unable to unpack a binary that UPX is able to unpack

### ISSUE THREAD

**Issue by s3rvac** [avast-tl/retdec#284]
Our unpacker is unable to unpack a binary that UPX is able to unpack.

## Input

Run
```
$ retdec-unpacker FILE
```
where `FILE` is
* [`34D393EDC95D0C29CC042FD5B4B3AE072C9B4ED06FC67773A34BF096C9EF484E`](https://www.virustotal.com/#/file/34d393edc95d0c29cc042fd5b4b3ae072c9b4ed06fc67773a34bf096c9ef484e/detection)

## Output

```
No matching plugins found for '7-Zip SFX 4.57'
No matching plugins found for 'Intel XE 13'
No matching plugins found for 'MSVC'
```

## Expected output

I would expect the unpacker to unpack the input binary file as I was able to unpack it via `upx`:
```
$ upx -d 34D393EDC95D0C29CC042FD5B4B3AE072C9B4ED06FC67773A34BF096C9EF484E
Ultimate Packer for eXecutables
   Copyright (C) 1996 - 2017
UPX 3.94        Markus Oberhumer, Laszlo Molnar & John Reiser   May 12th 2017

File size         Ratio      Format      Name
--------------------   ------   -----------   -----------
307200 <-  12708600  overlay   djgpp2/coff   34D393EDC95D0C29CC042FD5B4B3AE072C9B4ED06FC67773A34BF096C9EF484E

Unpacked 1 file.
```
We should investigate why `upx` is able to unpack it but our unpacker is not.

## Configuration

* Commit: 1647e9f63120421c66d16c6fb9b9777719023c2c (current `master`)
* 64b Arch Linux, GCC 7.3.1, Debug build of RetDec

**Comment by mbandzi** [comment]
This is bug in `cpdetect`. Old version of 7-Zip were using UPX to further compress SFX stub. It seems that 7-Zip detection somehow shadows UPX detection. 7-Zip should be detected only after UPX decompression. I will take look at this.

**Comment by mbandzi** [comment]
After further research I can conclude this is not a bug after all. The file is quiet strange binary that contains both MS-DOS executable that is compressed by UPX (not just common stub for printing 'cannot run under MS-DOS' warning). Portable Executable 'part of file' is 7-Zip SFX installer and is not UPX compressed. So we basically do not detect UPX and decompress the file because we do not support MS-DOS files.
