### ISSUE TITLE
Error setting up Windows 64b environment (error: failed retrieving file)

### ISSUE THREAD

**Issue by Const-me** [avast-tl/retdec#30]
`pacman -S tar upx bc wget`
fails saying following:

```
error: failed retrieving file 'ucl-1.03-1-x86_64.pkg.tar.xz' from repo.msys2.org : Maximum file size exceeded
error: failed retrieving file 'ucl-1.03-1-x86_64.pkg.tar.xz' from downloads.sourceforge.net : Maximum file size exceeded
error: failed retrieving file 'ucl-1.03-1-x86_64.pkg.tar.xz' from www2.futureware.at : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
```

**Comment by LordSk** [comment]
Workaround:
Download the package manually from repo.msys2.org, and do
`pacman -U "where your package is"`

**Comment by Const-me** [comment]
How do I find out the URL of these packages?
pacman doesn't prints URLs, only the server's DNS name.

**Comment by LordSk** [comment]
http://repo.msys2.org/msys/x86_64/ucl-1.03-1-x86_64.pkg.tar.xz

**Comment by boondoggler** [comment]
I figured out the above in parallel and it works a treat

**Comment by s3rvac** [comment]
Unfortunately, this seems to be a known bug in MSYS2:
* https://github.com/Alexpux/MSYS2-pacman/issues/49
* https://github.com/Alexpux/MSYS2-packages/issues/924
* https://github.com/Alexpux/MSYS2-packages/issues/942
* https://github.com/Alexpux/MSYS2-packages/issues/1025

As others have already suggested, the workaround is to download and install the offending package(s) manually.

**Comment by s3rvac** [comment]
We have added a mention of this issue into [our wiki](https://github.com/avast-tl/retdec/wiki/Windows-Environment#gnu-tar-upx-bc-wget-etc), including the abovementioned workaround. I am closing this issue as RetDec is not at fault here. Thanks to everyone who suggested the workaround!

**Comment by ChaosXTP** [comment]
Just Curious, I looked at the other replys, and I tried to find examples of installing packages manually but couldn't find any. Any help?

**Comment by s3rvac** [comment]
@ChaosXTP To install a package manually:
1. Download the package you need from one of the following links, depending on whether you have 32b or 64b MSYS2:
    * [packages for 32b MSYS2](http://repo.msys2.org/msys/i686/)
    * [packages for 64b MSYS2](http://repo.msys2.org/msys/x86_64/)
2. Open MSYS2 terminal.
3. Run `pacman -U <path-to-package.tar.xz>` and answer `Y` when asked whether to _Proceed with installation?_

**Comment by guoxiao** [comment]
`pacman -U <url-to-package.tar.xz>` also works, which is more convenience than download-and-install.
