### ISSUE TITLE
Cannot build RetDec in the Debug mode

### ISSUE THREAD

**Issue by dhucul** [avast-tl/retdec#302]
retdec compiles nicely in release mode but not in debug mode.
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$HOME/projects/retdec-install
[ 68%] Linking CXX static library libretdec-llvmir2hll.a
[ 68%] Built target retdec-llvmir2hll
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
any ideas why?

**Comment by s3rvac** [comment]
Hi. I assume that you are running on Linux. Could you please provide the following information?
* Run `make -j$(nproc) > log.txt 2>&1` and attach the `log.txt` file here.
* What commit are you trying to build (run `git rev-parse HEAD`)?
* What Linux distribution do you use?
* What CMake version do you use (run `cmake --version`)?
* What compiler do you use? Run e.g. `gcc --version` if you use GCC.

**Comment by dhucul** [comment]
Thanks for the help. I ran make -j$(nproc) > log.txt 2>&1 as you suggested and went through the log file and found missing "keystone.h".  Downloaded the package keystone from github. I compiled and install it and everything worked fine.

**Comment by s3rvac** [comment]
Could you please provide the requested information anyway? It seems that we have a bug in the build system as the error that you get should never happen (keystone is built as part of RetDec build). We would like to investigate the issue, and to do this, we need to be able to reproduce the bug.

**Comment by s3rvac** [comment]
I have checked our build system. The only targets that depend on keystone are `capstone2llvmirtool` and tests for `capstone2llvmir`. Both of them have `keystone` in their dependency list, so `keystone` should be automatically built before them. Are you sure that that the missing file was `keystone.h`? Maybe the build of `keystone` itself failed? Anyway, we are unable to reproduce the problem. It would help if you shared with us the type of your Linux distribution, CMake version, compiler version, and tested commit.

Nevertheless, what is the most interesting part is that `capstone2llvmirtool` and tests for `capstone2llvmir` are disabled by default, and you need to pass special options to `cmake` to enable them. You have reported that you used the following `cmake` command:
```
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$HOME/projects/retdec-install
```
This `cmake` command does not enable the two above-mentioned targets, and nothing that is built even uses `keystone`. Are you sure that this is the `cmake` command that you ran? Could you tell us what RetDec commit did you try to built?
