### ISSUE TITLE
Double lib prefix in compiled libraries

### ISSUE THREAD

**Issue by HugoKlepsch** [avast-tl/retdec#31]
The libraries liblibdwarf.so & liblibelf.so have an extra 'lib'. 

The contents of CMAKE_INSTALL_PREFIX/lib:
```
-rw-r--r-- 1 hugo hugo 318K Dec 14 11:14 liblibdwarf.so
-rw-r--r-- 1 hugo hugo 132K Dec 14 11:14 liblibelf.so
```

Changing this should be as simple as editing a few CMakeLists.txt. I may look into this in the next few days.

**Comment by s3rvac** [comment]
Hi. Yes, you are right. We plan to rename these two libraries to `libretdec-libelf.so` and `libretdec-libdwarf.so` so there won't be any clashes with standard `libelf.so` and `libdwarf.so` libraries in cases when a user performs a system-wide installation of RetDec (this is not supported at the moment).

**Comment by PeterMatula** [comment]
Fixed in https://github.com/avast-tl/libdwarf/commit/b7441146672bf38f175371714825b2fc757fbc4f

I hope I updated submodules correctly and it is in `retdec`. Don't forget to run `git submodule update --recursive` after `git pull`.
