### ISSUE TITLE
New logo?

### ISSUE THREAD

**Issue by hendrykeren** [avast-tl/retdec#313]
Hello sir.
You have a great app, unfortunately this app does not have a logo yet, may I donate a logo for your app?

**Comment by MerovingianByte** [comment]
Haha, I'd say why not, but I'm not part of the team. I want to see the issues tab showing the number 0 xD

**Comment by s3rvac** [comment]
Hi. Thank you for your offer, but we actually have a new logo. We just have not managed to put it up yet. However, I believe we should get to it soon.
