### ISSUE TITLE
Missing fclose() in PDBFile::load_pdb_file()

### ISSUE THREAD

**Issue by maddin200** [avast-tl/retdec#316]
\src\pdbparser\pdb_file.cpp line 48:
missing fclose(fp);

**Comment by s3rvac** [comment]
Thank you for the report. I have fixed this in ef548e8562f986fca8e3cd2e19a9ffeff4480a4e. The PDB-parsing library would benefit from a complete rewrite as the current implementation is low-quality and hard to extend (#109).
