### ISSUE TITLE
decoder.cpp in bin2llvmir contains an identical if condition

### ISSUE THREAD

**Issue by maddin200** [avast-tl/retdec#319]
\src\bin2llvmir\optimizations\decoder\decoder.cpp line 2613
identical condition   else if (ds) same as above

**Comment by s3rvac** [comment]
This file is being heavily modified by @PeterMatula in branch `issue-116`, and the code does no longer seem the be present in there. @PeterMatula, can you please verify? If so, we can close this issue as soon as we merge the branch into `master`.

**Comment by PeterMatula** [comment]
This entire module will be replaced by a new implementation. Even the current implementation in `issue-116` will be heavily refactored before merge.

**Comment by s3rvac** [comment]
Alright, so I am closing the issue as the fix would introduce merge conflicts later.
