### ISSUE TITLE
Decompilation of 64bit binaries?

### ISSUE THREAD

**Issue by pat-ford** [avast-tl/retdec#326]
Hi All;
 Trying to decompile a Ubuntu 64 bit elf, on a ubuntu box( Kubuntu 17.10).  The final output is:
Error: Unsupported target architecture 'X86-64'. Supported architectures: Intel x86, ARM, ARM+Thumb, MIPS, PIC32, PowerPC.

Is there any hope for an X86-64 target?
Thanks

**Comment by s3rvac** [comment]
Hi. Decompilation of 64b binaries is not yet support. However, there is an ongoing work in this direction (see #9).

**Comment by pat-ford** [comment]
Thanks for the info!
