### ISSUE TITLE
Memory leaks in demangler

### ISSUE THREAD

**Issue by Alexander-Alekseev** [avast-tl/retdec#329]
The 'temp_expr' pointer was assigned values twice without releasing the memory.

https://github.com/avast-tl/retdec/blob/f562afce6f41eb1414aa7261dd4697dd35a5031e/src/demangler/gparser.cpp#L920-L930

Currently I don't know how to fix it, because the `malloc` call is quite strange. Possible slutions are:
- either remove `malloc` call and following check,
- or (if you really need this `malloc` call) release memory after the check. For example:
```c
			temp_expr = malloc(sizeof(bool));
			if (temp_expr == nullptr) {
				all_ok = false;
				break;
			}
                        free(temp_expr);
			temp_expr = static_cast<bool *>(i->value);
````

**Comment by Alexander-Alekseev** [comment]
I noticed that current demangler has to be rewritten or replaced (https://github.com/avast-tl/retdec/issues/95), but I think that until it's done, the fix of memory leak would be helpful.

**Comment by s3rvac** [comment]
Thank you for report. Yes, there is indeed a memory leak, and yes, the demangler is ripe for a complete rewrite, as its current code is a huge mess. In commit 7893e003317adf5c8170d6b22de05c464e1d9fbd, I have fixed this memory leak by writing what the original author probably intended (the code dates back to 2012, and its author is gone).
