### ISSUE TITLE
Many functions are marked as "unreachable".

### ISSUE THREAD

**Issue by 0xBEEEF** [avast-tl/retdec#347]
I've been playing around with RetDec with an old file that I still had on my PC. It is still executable today. What struck me is that many functions are recognized with abort(). That struck me right away. [Here](https://www.virustotal.com/file/625dc8112bc509236ff5d0255b85cc0b82c9dd1ef27f6320a7394f33ab46800e/analysis) you can find the file on VirusTotal.

Examples of functions that have only one abort() or unreachable are the following:

- function_402ee0
- function_402f30
- function_403880

**Comment by palant** [comment]
Duplicate of #169?

**Comment by PeterMatula** [comment]
Fixed by merging #391 - see the added regression test.
