### ISSUE TITLE
Windows 10 Defender says that retdec-v3.1-windows-32b.zip contains Trojan:Win32/Azden.B!cl

### ISSUE THREAD

**Issue by ndk** [avast-tl/retdec#359]
Subj. https://www.virustotal.com/ru/file/c8425d1ad4423c3d44e89526f3ba375f5fe768e5e7197988351ed5502ddf24cf/analysis/1531767720/

**Comment by silverbacknet** [comment]
The funny thing about Trojan:Win32/Azden.B!cl is that every report of it on the internet is complaining about a false positive. I wouldn't be surprised if it was complaining about the unpacker, or the inclusion of cryptography libraries. Even crazier is that a number of others are suddenly detecting it as ransomware. Another instance of antivirus doing more harm than good.

https://www.microsoft.com/en-us/wdsi/antimalware-support/developer-resources is where you can report the Windows Defender alert, at least.

**Comment by PeterMatula** [comment]
We looked into this and we think it is clean. We reported this as a false positive to the relevant AVs.
