### ISSUE TITLE
Add parsing and presenting of referenced .NET types into fileinfo

### ISSUE THREAD

**Issue by s3rvac** [avast-tl/retdec#363]
Currently, `fileinfo` is able to parse and present classes, methods, etc. that are defined in the application. We would also utilize information on types that are referenced in the application but defined elsewhere. This will give us an overview about what types from the outside the application uses (e.g. from the standard library).

**Comment by metthal** [comment]
Implemented in 88df33d38e45c999af56d65ef8dc605b76682495.
