### ISSUE TITLE
hat happen to call graphs?

### ISSUE THREAD

**Issue by deepgray** [avast-tl/retdec#365]
when the code was online, there was a call graph output.

how do we reproduce that?

**Comment by TheCodez** [comment]
You have two command line options:
- `--backend-emit-cfg`: Emits a CFG for each function in the backend IR (in the .dot format).
- `--backend-emit-cg`: Emits a CG for the decompiled module in the backend IR (in the .dot format).

For example:
`$retdec-decompiler.sh test.exe --backend-emit-cfg`
