### ISSUE TITLE
  Could NOT find PythonInterp: Found unsuitable version "2.7.14", but   required is at least "3.4" (found /usr/local/bin/python)

### ISSUE THREAD

**Issue by massive44939** [avast-tl/retdec#381]
Someone please help me.

OSX, I have both python 2.7 installed and python 3.7 installed.

My PATH is /usr/local/opt/python3.7:/Library/Frameworks/Python.framework/Versions/3.7/bin/python3:/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

When I try to cmake it always says:

Could NOT find PythonInterp: Found unsuitable version "2.7.14", but
  required is at least "3.4" (found /usr/local/bin/python)

How do I fix this?

**Comment by s3rvac** [comment]
Hi. Two things:
1) When you run `python --version` and `python3 --version`, what do these commands print?
2) Is the following portion of your `PATH` correct?
    ```
    /usr/local/opt/python3.7:/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
    ```
   Entries in `PATH` should point to _directories_ that contain executables. I am not a macOS user, so I may be wrong, but it feels like you should use the following paths instead:
    ```
    /usr/local/opt/python3.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin
    ```
   Can you please try to modify your `PATH` in this way, remove everything from the `retdec/build` directory and retry running `cmake`?

**Comment by massive44939** [comment]
thank you. I ended up using a reddittors suggestion instead, but either way thank you so much.
I have another issue though, can you please help me with that instead? It's the newest issue after this one. Thank you for your time.

**Comment by s3rvac** [comment]
Could you please write here what you have done to fix the issue? Maybe other people will find it useful.

**Comment by nickolai-voyage** [comment]
https://xkcd.com/979/

**Comment by graphitical** [comment]
I had a similar issue. Turned out I didn't have any Python 3 version installed (just 2.7.10).
I installed python 3.7.4 via Homebrew (running OSX 10.14.5) and then tried again.
The install failed with the same error again.

I then found this solution (https://github.com/YosysHQ/nextpnr/issues/214) and removed/renamed my CMakeCache.txt file and this seemed to fix it.

**Comment by s3rvac** [comment]
@graphitical Thank you for the comment. Yes, if you install Python 3 **after** you have already run `cmake`, you need to remove `CMakeCache.txt` before trying the build again as CMake remembers what it has found the first time it has run.
