### ISSUE TITLE
Build is failing on macOS (FLEX_INCLUDE_DIR is set to NOTFOUND)

### ISSUE THREAD

**Issue by massive44939** [avast-tl/retdec#382]
mac os, error when typing make -j2. It gives me the following and then eventually a "make*** [all] error 2"

CMake Error at /Users/x/Downloads/retdec-master 3/build/external/src/yaramod-project-stamp/yaramod-project-configure-Release.cmake:16 (message):
  Command failed: 1

   '/usr/local/Cellar/cmake/3.12.1/bin/cmake' '-DCMAKE_BUILD_TYPE=Release' '-DCMAKE_C_COMPILER=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc' '-DCMAKE_CXX_COMPILER=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++' '-GUnix Makefiles' '/Users/x/Downloads/retdec-master 3/build/external/src/yaramod-project'

**Comment by metthal** [comment]
Could you attach the file `/Users/x/Downloads/retdec-master 3/build/external/src/yaramod-project-stamp/yaramod-project-configure-Release.cmake`?

**Comment by s3rvac** [comment]
And also the following two log files please:
* `/Users/x/Downloads/retdec-master 3/build/external/src/yaramod-project-stamp/yaramod-project-configure-err.log`
* `/Users/x/Downloads/retdec-master 3/build/external/src/yaramod-project-stamp/yaramod-project-configure-out.log`

**Comment by massive44939** [comment]
how do I attach the file 

/Users/x/Downloads/retdec-master 3/build/external/src/yaramod-project-stamp/yaramod-project-configure-Release.cmake?

**Comment by massive44939** [comment]
here is the yaramod-project-configure-release:
set(command "/usr/local/Cellar/cmake/3.12.1/bin/cmake;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_C_COMPILER=/Applications/Xcode.app/Co$
execute_process(
  COMMAND ${command}
  RESULT_VARIABLE result
  OUTPUT_FILE "/Users/x/Downloads/retdec-master 3/build/external/src/yaramod-project-stamp/yaramod-project-configure-out.lo$
  ERROR_FILE "/Users/x/Downloads/retdec-master 3/build/external/src/yaramod-project-stamp/yaramod-project-configure-err.log"
  )
if(result)
  set(msg "Command failed: ${result}\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  set(msg "${msg}\nSee also\n  /Users/x/Downloads/retdec-master 3/build/external/src/yaramod-project-stamp/yaramod-project-$
  message(FATAL_ERROR "${msg}")
else()
  set(msg "yaramod-project configure command succeeded.  See also /Users/x/Downloads/retdec-master 3/build/external/src/yar$
  message(STATUS "${msg}")

**Comment by s3rvac** [comment]
Have you installed [Flex](https://www.gnu.org/software/flex/) and [Bison](https://www.gnu.org/software/bison/) via Homebrew and set the following variables before running `cmake`, as requested in our [build instructions for macOS](https://github.com/avast-tl/retdec#process)?
```
# Apple ships old Flex & Bison, so Homebrew versions should be used.
export CMAKE_INCLUDE_PATH="/usr/local/opt/flex/include"
export CMAKE_LIBRARY_PATH="/usr/local/opt/flex/lib;/usr/local/opt/bison/lib"
export PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"
```

**Comment by s3rvac** [comment]
@massive44939 Based on [this comment](https://github.com/avast-tl/retdec/issues/103#issuecomment-417179226), the above solution should fix the problem. Please verify. If this solution fixes the problem for you, you can close the issue.

**Comment by s3rvac** [comment]
I am closing this issue as we have not received any feedback in the last three weeks. Feel free to reopen it if the above solution does not work for you.
