### ISSUE TITLE
LOG_TIME = ['/usr/bin/time', '-v'] in retdec-config.py option "-v" not valid on macOS

### ISSUE THREAD

**Issue by bmourit** [avast-tl/retdec#383]
The version in /usr/bin/time on macOS does not accept the '-v' option. The workaround is to install gnu-time from homebrew which would then be under /usr/local/bin/gtime. If I get time, I may post a fix for this, but for now just reporting the issue.

**Comment by PeterMatula** [comment]
This command gets used only with option `--generate-log`. This is an internal option that was not meant to be used by the users. I hid it in commit d871f1e. We use it in internal tests that run on Linux servers and track decompilator's time and memory consumption. It was never meant to be run on macOS or Windows.

This issue can stay open if someone wants to make it portable to macOS (send a pull request), but we (RetDec team) will not be fixing this ourselves.

**Comment by bmourit** [comment]
Thanks for the response. I only came across this while debugging. I thought it might be useful for anyone wishing to contribute/develop in the future. Thanks!

**Comment by s3rvac** [comment]
A note for people who try to fix this issue: Removing the `-v` parameter on macOS does not represent a full solution as our scripts assume that `/usr/bin/time` is run with `-v`. Apart from other information, the `-v` parameter makes `/usr/bin/time` produce memory usage of the tracked program, which we then parse in our scripts. Without `-v`, the used memory will always be 0, which will make results incorrect.
