### ISSUE TITLE
Function names matched but not present in output

### ISSUE THREAD

**Issue by PGAnonamous** [avast-tl/retdec#405]
So I am using a specified yara rule and I have gotten matches in the generated json file. However when I open the outputted c file none of the function have actually been named. What do I need to do to have them named in the output? Passing the --static-code-sigfile and --static-code-archive doesn't even cause detection in the json file so I changed the FILEINFO_EXTERNAL_YARA_PRIMARY_CRYPTO_DATABASES and FILEINFO_EXTERNAL_YARA_EXTRA_CRYPTO_DATABASES to point to the signatures I wanted. This cause the json file to detect them and match them but they are still named function_229ed0 (for example) in the output c file.

**Comment by s3rvac** [comment]
Hi. Please, provide the following information:
* What version of RetDec do you use (e.g. release 3.2, current `master`)?
* What decompilation command did you run? Do not forget to attach all the input files that we will need to run the decompilation command.
* What did you expect to obtain as output from the decompilation?
* What was the actual output from the decompilation?

**Comment by PGAnonamous** [comment]
@s3rvac 

     Thank you for your assistance. Strangely enough I am unable to reproduce it using an example. My only thoughts could be that it didn't name the function in the output due to a recovery after running out of memory. I will close this and keep trying.

**Comment by s3rvac** [comment]
Alright, no problem. If you stumble upon the reported issue in the future, feel free to reopen.
