### ISSUE TITLE
retdec-macho-extractor file missing from scripts directory

### ISSUE THREAD

**Issue by kostaskol** [avast-tl/retdec#418]
Whenever I try to use the `retdec-decompiler.py` script, I get the following error:
`FileNotFoundError: [Errno 2] No such file or directory: '</path/to/>retdec/scripts/retdec-macho-extractor': '</path/to>/retdec/scripts/retdec-macho-extractor'`

OS: Kali linux Rolling

I would be happy to provide any further information that might be needed.

**Comment by s3rvac** [comment]
Hi. Have you [built and installed](https://github.com/avast-tl/retdec#build-and-installation) RetDec before running the script? The error you have posted shows up when you try to run `retdec/scripts/retdec-decompiler.py` instead of `<install dir>/bin/retdec-decompiler.py`.

**Comment by s3rvac** [comment]
To improve the error that is being shown in this case, I have added a check into the scripts that they are run from an installed RetDec (commit c9673dbb22c7e1c182cd7e5878aca7b1804d2c19). If anyone tries to run them from the `scripts` directory, they will see the following error message:
```
Error: You need to build and install RetDec first and then run the installed script via `python $RETDEC_INSTALL_DIR/bin/retdec-decompiler.py`.
For more details, see https://github.com/avast-tl/retdec#installation-and-use
```
This makes the issue self-evident.

**Comment by kostaskol** [comment]
I really can't believe it but I forgot to `make install` after make, so it's entirely my fault. Thank you for your help and sorry for taking up your time for something as silly as this.
