### ISSUE TITLE
Installation on OSX fails with "ERROR: download failed: SSL: CERTIFICATE_VERIFY_FAILED"

### ISSUE THREAD

**Issue by jazz-2438** [avast-tl/retdec#420]
I'm getting this error when running `make install` on OSX. 

`Install the project...
-- Install configuration: "Release"
Downloading archive from https://github.com/avast-tl/retdec-support/releases/download/2018-02-08/retdec-support_2018-02-08.tar.xz ...
ERROR: download failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
CMake Error at cmake_install.cmake:43 (message):
  RetDec share directory installation FAILED
make: *** [install] Error 1`

I had originally had OpenSSL errors so I used these parameters with cmake:

`build jason$ cmake -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2p -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl/1.0.2p/lib .. -DRETDEC_DOC=ON -DCMAKE_INSTALL_PREFIX=$HOME/projects/retdec-install
`

OpenSSL then seemed to work fine:

`-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
-- Found OpenSSL: /usr/local/Cellar/openssl/1.0.2p/lib/libcrypto.dylib (found suitable version "1.0.2p", minimum required is "1.0.1")  
-- Found FLEX: /usr/bin/flex (found version "2.5.35") 
-- Found BISON: /usr/bin/bison (found version "2.3") 
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.14") found components:  doxygen dot 
-- Configuring done
-- Generating done`

In my install directory, "share" folder is created with only an empty "retdec" folder within it

**Comment by s3rvac** [comment]
Hi. It seems to me that you have some issues with OpenSSL or certificates in your system. Could you please try running the following command from a terminal?
```
curl -L https://github.com/avast-tl/retdec-support/releases/download/2018-02-08/retdec-support_2018-02-08.tar.xz --output retdec-support_2018-02-08.tar.xz
```
If it fails, then the issues you have are not related to RetDec but probably to your OpenSSL installation.

**Comment by s3rvac** [comment]
Alright, then let's see if the issues are in your Python installation. Create a file named `test.py` with the following content:
```
import urllib.request

urllib.request.urlretrieve(
    'https://github.com/avast-tl/retdec-support/releases/download/2018-02-08/retdec-support_2018-02-08.tar.xz',
    'retdec-support_2018-02-08.tar.xz'
)
```
and run it via
```
python3 test.py
```
(Or just `python test.py` if `python` points to Python 3 and not Python 2).

If the downloading fails with the reported error, then there is a certificate/OpenSSL-related issue with the Python installation in your system. Unfortunately, we do not have a macOS machine that we could use to try to reproduce the issue. Could you check [this SO question and answer](https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore)?

**Comment by s3rvac** [comment]
A probably related info from [Python 3.6 release notes](https://www.python.org/downloads/release/python-360/) that is being referenced from various forums dealing with a similar issue:
> macOS users: If you are using the Python 3.6 from the python.org binary installer linked on this page, please carefully read the Important Information displayed during installation; this information is also available after installation by clicking on /Applications/Python 3.6/ReadMe.rtf. There is important information there about changes in the 3.6.0 installer-supplied Python, particularly with regard to SSL certificate validation.

**Comment by jazz-2438** [comment]
Awesome! 

test.py failed with some SSL failure
I followed the SO answer. In the python 3.7 folder inside the application folder there's already a shell "Install Certificates.command". Just double clicked that and it test.py worked. 

The archive successfully downloaded and is now unpacking. Crossing my fingers everything else goes smoothly.

Thank you so much for your swift and effective responses!

**Comment by s3rvac** [comment]
Great :+1:
