### ISSUE TITLE
Unable to start program C:\retdec\build\x64\Debug\ALL_BUILD Access is denied. MS VS 2015/2017

### ISSUE THREAD

**Issue by PavelKotov1** [avast-tl/retdec#426]
Hello, dear friends!
I am trying to figure out how to set up debugging environment for retdec in MS VS 2017, so I follow the instructions found here:
https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2017#enable-mixed-mode-debugging-in-a-cc-project
 to enable mixed-mode debugging in a C/C++ project. 
When I try to "Start without debugging", I see this message 
"Unable to start program C:\retdec\build\x64\Debug\ALL_BUILD Access is denied."
 It happens both on VS 2015 and 2017 (15.8.6)
OS Name	Microsoft Windows 7 Professional
Version	6.1.7601 Service Pack 1 Build 7601

I am very new to the project of this complexity and may approach this in a totally wrong way. So hopefully you could help me to figure out this whole situation and explain if possible step by step how to debug this program. 
Your help is greatly appreciated!

PS
I guess what confuses me the most is the fact, that there is no separate python project. 
Microsoft says: 
**_Enable mixed-mode debugging in a Python project
1.Right-click the Python project in Solution Explorer, select Properties, select the Debug tab, and then select Enable native code debugging. This option enables mixed-mode for all debugging sessions._**

And that is where i am completely lost...

**Comment by silverbacknet** [comment]
Check the permissions on your retdec folder. It might be inheriting from C:\ which is rather locked down, and if you have different processes running at different authority levels, access denials will happen. Give Everyone Modify or Full Access permission to that folder to fix that.

Retdec doesn't have a Python project, you just have to put the command to run the retdec in the debugger and wait until it gets to the actual C process if you want to debug the internals. Debugging the Python part has to be done in pdb, but contributions are always welcome for a VS-compatible Python project.

**Comment by PavelKotov1** [comment]
Thanks for your answer! 
Unfortunately, for a person like myself with a limited experience in the matter, it is still not clear. Please, do not judge me too harshly, but if possible provide clear, step by step instructions. If Visual Studio part makes matters complicated, let's forget about it and use any other debugger available. 
You obviously know how to debug your own product, please describe how you do that using any debugger that you use but please be specific (literally, step by step). 
Thanks again, hope to hear from you soon! 
Kind regards, PK

**Comment by PavelKotov1** [comment]
Hello, there!
Just making sure if I should expect an answer to my question or simply forget about the whole thing.
Actually, I am surprised that you make your (brilliant!) code public and put it out there for all to see but could not share a secret way of debugging it.
I would settle for any debugging scenario as long as it works.
Still hope to hear an answer!
Kind regards!

**Comment by s3rvac** [comment]
Hello @PavelKotov1. As I wrote [here](https://github.com/avast-tl/retdec/issues/423#issuecomment-435645398), what you basically need is to (1) run `retdec-decompiler.py` to get a list of commands that have been run to decompile the input file and then (2) run these commands in VS in the debugging mode. This pretty much boils down to ordinary debugging of applications in VS and has little to do with RetDec. Unfortunately, almost none of us uses VS, so I am afraid we will not be able to help you in this regard (hence the `D-help-wanted` label).

> You obviously know how to debug your own product, please describe how you do that using any debugger that you use but please be specific (literally, step by step).

Here is what I do to debug decompilation of an imaginary file `test.exe` on Linux with [gdb](https://www.gnu.org/software/gdb/) (warning: this will probably won't work on Windows with RetDec built via VS as VS uses a different format of debugging information than gdb):
1. Just for completeness, you will need a debug build of RetDec (pass `-DCMAKE_BUILD_TYPE=Debug` to `cmake` when building RetDec).
2. Run
    ```
    retdec-decompiler.py test.exe
    ```
    which prints the list of commands you can run in `gdb`.
3. Pick one of these commands, e.g.
    ```
    /path/to/bin/retdec-fileinfo -c /path/to/test.c.json --similarity /path/to/bin/test.exe --no-hashes=all --crypto /path/to/share/retdec/support/generic/yara_patterns/signsrch/signsrch.yara --max-memory-half-ram
    ```
4. Run this command in `gdb` and set a breakpoint on `main()`:
    ```
    $ gdb -quiet /path/to/retdec-fileinfo
    Reading symbols from /path/to/bin/retdec-fileinfo...done.
    (gdb) break main
    Breakpoint 1 at 0x120ba6: file /path/to/src/fileinfo/fileinfo.cpp, line 401.
    (gdb) run -c /path/to/test.c.json --similarity /path/to/bin/test.exe --no-hashes=all --crypto /path/to/share/retdec/support/generic/yara_patterns/signsrch/signsrch.yara --max-memory-half-ram
    Starting program: /path/to/bin/retdec-fileinfo -c /path/to/test.c.json --similarity /path/to/bin/test.exe --no-hashes=all --crypto /path/to/share/retdec/support/generic/yara_patterns/signsrch/signsrch.yara --max-memory-half-ram
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/usr/lib/libthread_db.so.1".

    Breakpoint 1, main (argc=7, argv=0x7fffffffdc48) at /path/to/src/fileinfo/fileinfo.cpp:401
    401     {
    (gdb)
    ```
    After this, you can continue debugging from `main()`.

**Comment by PavelKotov1** [comment]
Dear Petr!
This is perfect, exactly what I needed!
Now I can start learning your wonderful tool!
Thanks  a bunch!

**Comment by olii** [comment]
If you want to run the program in Visual Studio and you get the "Unable to start program C:\retdec\build\x64\Debug\ALL_BUILD Access is denied." you should set the appropriate binary to be run. 

As you can see `C:\retdec\build\x64\Debug\ALL_BUILD` is not an executable. To run the binary of your desire, you should set the active project in VS that generates this binary. You can do it by clicking on the project and select `Set as startup project`. Then you can run or debug this binary without problems. 

Keep in mind, there are multiple binaries in this project. You should know which one you want to debug.
If you are in trouble, google for `"Set as startup project"`.

**Comment by Lionberg** [comment]
This error exists in VS 2022 too. And I try to build a Setup Project that makes distributable MSI of my other project. And during a build I get Access Denied error, while running VS as Administrator and giving all possible rights to that folder. Who on Earth has more rights to access then a Super User?.. Oh, dear Microsoft...
