### ISSUE TITLE
yaracpp build fails with "configure: error: cannot run C compiled programs"

### ISSUE THREAD

**Issue by iinus** [avast-tl/retdec#433]
Hello, I'm having trouble with installing recdec. I have been following the prerequisites and looked at #291, but none of it work. Here is my error output: 

[ 71%] Building CXX object src/loader/CMakeFiles/retdec-loader.dir/loader/segment.cpp.o
CMake Error at /Users/iinusen/Documents/retdec/external/src/yaracpp-project-stamp/yaracpp-project-build-Release.cmake:16 (message):
  Command failed: 2

   '/Library/Developer/CommandLineTools/usr/bin/make'

  See also

    /Users/iinusen/Documents/retdec/external/src/yaracpp-project-stamp/yaracpp-project-build-*.log

make[2]: *** [external/src/yaracpp-project-stamp/yaracpp-project-build] Error 1
make[1]: *** [deps/yaracpp/CMakeFiles/yaracpp-project.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 71%] Building CXX object src/loader/CMakeFiles/retdec-loader.dir/loader/intel_hex/intel_hex_image.cpp.o
[ 71%] Building CXX object src/loader/CMakeFiles/retdec-loader.dir/loader/macho/macho_image.cpp.o
[ 71%] Building CXX object src/loader/CMakeFiles/retdec-loader.dir/loader/raw_data/raw_data_image.cpp.o
[ 72%] Linking CXX executable retdec-llvmir2hll
[ 72%] Building CXX object src/loader/CMakeFiles/retdec-loader.dir/loader/elf/elf_image.cpp.o
[ 72%] Built target retdec-llvmir2hlltool
[ 72%] Linking CXX static library libretdec-loader.a
[ 72%] Built target retdec-loader
make: *** [all] Error 2
[log.txt](https://github.com/avast-tl/retdec/files/2624900/log.txt)

I also attached the full log file.

**Comment by s3rvac** [comment]
Hi. Could you please attach the following two log files?
```
/Users/iinusen/Documents/retdec/external/src/yaracpp-project-stamp/yaracpp-project-build-err.log
/Users/iinusen/Documents/retdec/external/src/yaracpp-project-stamp/yaracpp-project-build-out.log
```
They contain the reason why the `yaracpp` build failed.

**Comment by iinus** [comment]
[yaracpp-project-build-out.log](https://github.com/avast-tl/retdec/files/2625759/yaracpp-project-build-out.log)
[yaracpp-project-build-err.log](https://github.com/avast-tl/retdec/files/2625761/yaracpp-project-build-err.log)

**Comment by s3rvac** [comment]
Thank you. From `yaracpp-project-build-err.log`, it seems to be the same error as in #425. Could you please try [this approach](https://github.com/avast-tl/retdec/issues/425#issuecomment-435698129) to see whether it fixes the problem for you?

**Comment by iinus** [comment]
Thank you, it worked!

**Comment by s3rvac** [comment]
Great :+1:
