### ISSUE TITLE
decompile fails with: Global variable initializer type does not match global variable type

### ISSUE THREAD

**Issue by fesc2000** [avast-tl/retdec#436]
The mentioned error happens during 
...
Running phase: Assembly Writer ( 14.24s )

There are several references to this error in https://github.com/ldc-developers. Could this come from outdated llvm code?

[log.txt](https://github.com/avast-tl/retdec/files/2635834/log.txt)

**Comment by fesc2000** [comment]
Here it comes:

[ci.zip](https://github.com/avast-tl/retdec/files/2635860/ci.zip)

**Comment by s3rvac** [comment]
Thank you for the report. I can confirm that there is indeed an issue when decompiling the file you have attached. On the current `master`, the debug version of RetDec fails with the following error:
```
Running phase: Constants optimization ( 6.36s )
While deleting: i32* %global_var_806da00
Use still stuck around after Def is destroyed:@global_var_806dbb0.481 = global i32* @global_var_806da00
retdec-bin2llvmir: build/external/src/llvm-project/lib/IR/Value.cpp:85: virtual llvm::Value::~Value(): Assertion `use_empty() && "Uses remain when a value is destroyed!"' failed.
Error: Decompilation to LLVM IR failed
```
@PeterMatula, could you please take a look?

**Comment by PeterMatula** [comment]
The binary was added to our internal tests, since in this case we don't need to check the output quality but only that the decompilation succeeds.

**Comment by fesc2000** [comment]
Fix confirmed, thanks a lot!

Am Do., 28. Feb. 2019 um 14:23 Uhr schrieb Peter Matula <
notifications@github.com>:
