### ISSUE TITLE
Error: Option -a|--arch must be used with format ihex

### ISSUE THREAD

**Issue by ClareMiller** [avast-tl/retdec#445]
When I attempt to use the retdec-decompiler.py I get the following:

C:\Users\c.miller\Desktop>py -3 retdec/bin/retdec-decompiler.py 78333865D_09_14_16.hex
##### Checking if file is an archive...
RUN: C:\Users\c.miller\Desktop\retdec\bin\retdec-ar-extractor C:\Users\c.miller\Desktop\78333865D_09_14_16.hex --arch-magic
Not an archive, going to the next step.
##### Gathering file information...
RUN: C:\Users\c.miller\Desktop\retdec\bin\retdec-fileinfo -c C:\Users\c.miller\Desktop\78333865D_09_14_16.hex.c.json --similarity C:\Users\c.miller\Desktop\78333865D_09_14_16.hex --no-hashes=all --crypto C:\Users\c.miller\Desktop\retdec\bin\..\share\retdec\support\generic\yara_patterns\signsrch\signsrch.yara --max-memory-half-ram
Input file               : C:\Users\c.miller\Desktop\78333865D_09_14_16.hex
File format              : Intel HEX
File type                : Executable file
Warning: Invalid address of entry point.
##### Trying to unpack C:\Users\c.miller\Desktop\78333865D_09_14_16.hex into C:\Users\c.miller\Desktop\78333865D_09_14_16.hex-unpacked.tmp by using generic unpacker...
RUN: C:\Users\c.miller\Desktop\retdec\bin\retdec-unpacker C:\Users\c.miller\Desktop\78333865D_09_14_16.hex -o C:\Users\c.miller\Desktop\78333865D_09_14_16.hex-unpacked.tmp --max-memory-half-ram
##### 'upx' not available: nothing to do
Error: Option -a|--arch must be used with format ihex

I am using Windows 10 64 bit.

**Comment by s3rvac** [comment]
Hi. Unlike ELF, PE, and Mach-O, there is no way of automatically detecting the architecture from files in the Intel HEX format. Thus, when decompiling Intel HEX files, you need to specify the architecture manually via `-a/--arch`.
