### ISSUE TITLE
failed to decompile function: startswith first arg must be bytes or a tuple of bytes, not str

### ISSUE THREAD

**Issue by trippleflux** [avast-tl/retdec#453]
I am getting error 
```
failed to decompile function: startswith first arg must be bytes or a tuple of bytes, not str
```
When using the lates dev build of binaryninja, [retdec_offline](https://github.com/ThisIsSecurity/retdec_offline),python 3.7.2, and self-compiled x64 windows retdec vanilla git branch.

already tried to add b infront of bytes in the startswith but still failed to invoke retdec, for example : 
````
self.args.raw_entry_point = int(self.args.raw_entry_point, 16 if self.args.raw_entry_point.startswith(b'0x') else 10)
````

**Comment by silverbacknet** [comment]
self.args.selected_ranges, and therefore all of its descendants, should be a string. How are you calling it?

**Comment by s3rvac** [comment]
Hi. I believe this is not a RetDec error as RetDec itself does not provide a Python API. I think you will have better luck when you report this issue to either Binary Ninja or retdec_offline (I am not sure which one).

**Comment by trippleflux** [comment]
The log only showing as this : 
````
retdec-decompiler.py --backend-no-debug-comments --cleanup --mode raw --raw-section-vma 0x43e52d --raw-entry-point 0x43e52d --arch x86 --endian little --config C:\Users\nameless\AppData\Local\Temp\tmpdtqo3k_b C:\Users\nameless\AppData\Local\Temp\tmpaf7tan9t
Warning: Unknown compiler or packer.
failed to decompile function: startswith first arg must be bytes or a tuple of bytes, not str
````

Manually invoking retdec without without through the retdec_offline binaryninja plugin resulting no error :-/

**Comment by s3rvac** [comment]
Are you sure that the `startswith first arg must be bytes or [..]` error that you are getting comes from RetDec? I have a reason to believe that it comes from retdec_offline and RetDec has nothing to do with this. I suggest you to submit a bug report to retdec_offline.

**Comment by silverbacknet** [comment]
Yep, the error is in retdec_offline:

>             p = Popen(self._cmdline, stdout=PIPE, stderr=PIPE, shell=True)
>             _, err = p.communicate()
>             log.log_info(err)
>             if err.startswith('Error'):

Popen return bytes unless text=true.
