### ISSUE TITLE
ELF files LIEF vs. RetDec

### ISSUE THREAD

**Issue by Hurdik** [avast-tl/retdec#457]
fileinfo provides lesser info on imported libraries in  ~1/20 cases than lief library.

**Comment by PeterMatula** [comment]
Solved by https://github.com/avast-tl/retdec/pull/468.

**Note:** We received a list of test sample hashes (cca 23000) and scripts to compare the outputs of LIEF and RetDec (needed dynamic libs and imported functions). Oftentimes LIEF provided more info. After changes in the referenced PR, RetDec is not missing any information compared to LIEF in the tested samples - it is at least as good as LIEF.
