### ISSUE TITLE
How to use retdec-bin2llvmirtool?

### ISSUE THREAD

**Issue by Youlor** [avast-tl/retdec#459]
How to specify input file? Thanks!

**Comment by s3rvac** [comment]
Hi. As you can see [in our README](https://github.com/avast-tl/retdec#installation-and-use), files should be decompiled via `retdec-decompiler.py`:
```
python $RETDEC_INSTALL_DIR/bin/retdec-decompiler.py FILE
```
This script runs all the necessary tools for you. One of these tools is `retdec-bin2llvmir`. So, you should not use `retdec-bin2llvmir` directly. Use `retdec-decompiler.py` instead.
