### ISSUE TITLE
fileinfo: Corruption check needs to distinguish between "file is cut" and "file is cut, but executable"

### ISSUE THREAD

**Issue by ladislav-zezula** [avast-tl/retdec#463]
Under some circumstances, a cut PE file might be still executable.

Examples:
82b82208e35402e11a68766f057cfdcabf5cd97c73ee5eeaa008548095597865 (32-bit)
8713f9a10a9e859b245031474acf770d719aab1f8cea1d957af41dea08019bc6 (64-bit)

Both these files were cut but are still loadable and executable, because the last PE section has physical size of 0.

We need a new class for file corruption: LDR_ERROR_FILE_IS_CUT_LOADABLE

**Comment by s3rvac** [comment]
Implemented by @ladislav-zezula in https://github.com/avast-tl/pelib/pull/5 (tests are in https://github.com/avast-tl/retdec-regression-tests/pull/16). Incorporated into RetDec in 5badadbdd2ab5e0e33a6fc3b1a782e42c8576e88.
