### ISSUE TITLE
retdec-v3.2-windows-32b.zip Getting flagged by Win 10 Defender as having a trojan

### ISSUE THREAD

**Issue by lanatmwan** [avast-tl/retdec#467]
I see that this was an issue the last version but 6 months later it is still getting flagged:

Trojan:Win32/Azden.A!cl
Category: Trojan

**Comment by s3rvac** [comment]
We have reported this issue to Microsoft. The file that is getting detected is `retdec-pat2yara.exe`, just like in #359, only 3.2 is a newer release.

**Comment by s3rvac** [comment]
Microsoft has replied:
> We have removed the detection.
>
> Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 1. Open command prompt as administrator and change directory to `c:\Program Files\Windows Defender`
> 2. Run `MpCmdRun.exe -removedefinitions -dynamicsignatures` Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

I have verified on VirusTotal that Microsoft tags it as _clean_.
