### ISSUE TITLE
retdec-bin2pat fails with "FileNotFoundError: The filename or extension is too long"

### ISSUE THREAD

**Issue by PGAnonamous** [avast-tl/retdec#472]
I am attempting to create a yara signature from the open-source ps2sdk through the retdec-signature-from-library-creator.py script. Upon running it I receive the error

FileNotFoundError: [WinError 206] The filename or extension is too long

Upon modifying retdec-utils.py to print out the arguments being passed to retdec-bin2pat.exe I can see that it is indeed too long. After copying the command into notepad++ I can see that it is a total of 118,999 characters long.

I did look into a way to get around this. You can see [here](https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation) that Microsofts recommends modifying programs that require long command lines to use a file that contains the parameter information instead. A good solution would appear to give an option to retdec-bin2pat to do so and have retdec-utils.py automatically pass them this way if they exceed a certain length.

**Comment by s3rvac** [comment]
Thank you for the report. The issue has been fixed by @astrelsky in #484 (thanks for the PR!).
