### ISSUE TITLE
CMake rules for pelib contain an unitialized variable

### ISSUE THREAD

**Issue by s3rvac** [avast-tl/retdec#478]
File `deps/pelib/CMakeLists.txt` contains the following piece of code:
```
44  # Force rebuild if switch happened.
45  # Seems like this is not needed on Linux, and not working on Windows :-(
46  BUILD_ALWAYS ${CHANGED}
```
However, the `CHANGED` variable is defined later on line
```
57  check_if_variable_changed(PELIB_LOCAL_DIR CHANGED)
```
Questions:
* Can you please verify that we actually want to use an uninitialized variable there?
* Is that `BUILD_ALWAYS` part necessary? According to the comment above, it is not needed on Linux and does not work on Windows. Is it for macOS then?

**Comment by PeterMatula** [comment]
- No, we don't want to use uninitialized variable. This must have happened as I was moving the code around.
- As the comment says, it was not working anyway. I probably only saw it used somewhere and added it just in case.

I just removed this line. It should not be worse without it.
