### ISSUE TITLE
Regression tests timeout from time to time

### ISSUE THREAD

**Issue by s3rvac** [avast-tl/retdec#479]
Some of our regression tests timeout from time to time. For an example, see [this macOS build](https://retdec-tc.avast.com/viewLog.html?buildId=1083&buildTypeId=Retdec_MacBuild&tab=buildLog). I have seen the timeouts on both macOS and Linux, but maybe this is also an issue on Windows. I strongly believe that these timeouts are caused by non-determinism in our tools (#209, #129). Instead of keeping disabling failing tests (#266), we should try to debug this.

[Here](https://github.com/avast-tl/retdec/files/2811071/TestNewARM32Signatures-outputs.zip) is an example of two `.ll` files produced by `bin2llvmir` in two separate runs of the `features.new-static-code-signatures.TestNewARM32Signatures` regression test on my Linux machine. As you can see, they differ on quite a lot of places. @PeterMatula, do you have an idea what is causing these differences?

**Comment by s3rvac** [comment]
More timeouts on macOS: https://retdec-tc.avast.com/viewLog.html?buildId=1249&buildTypeId=Retdec_MacBuild&tab=buildLog&_focus=5200

@PeterMatula Can you please take a look at this issue?

**Comment by PeterMatula** [comment]
Fixed in 55d46b5, all previously disabled tests enabled in https://github.com/avast-tl/retdec-regression-tests/commit/87dd055a96d4a512204082ec1dabedaa2505b7b4.
