### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by FFY00** [avast-tl/retdec#48]
You should consider use the repo tool by google for your build system. We are cloning and building the same repositories over and over again because you don't use a shared folder for all of your dependencies. This results in big repository size, using a lot of unnecessary processing power, using a lot of unnecessary time and a messy cmake build.

Take a look a this project which is using repo: https://github.com/aurora-fw
Repo Tool: https://source.android.com/setup/using-repo

**Comment by PeterMatula** [comment]
This was already discussed in #14.

Yes, there are multiple copies of repositories in `/deps/` folders. But nothing should be built multiple times, incremental build should work. So what do you mean by?
> building the same repositories over and over again
> unnecessary processing power
> messy cmake build

If there are some issues with this that we are not aware, please list them here and reopen this issue.

**Comment by Manouchehri** [comment]
Also see #8.
