### ISSUE TITLE
Fico order vs SCC order?

### ISSUE THREAD

**Issue by dberlin** [avast-tl/retdec#500]
(Filing an issue so someone can tell me whether i'm dumb :P)

While looking at the SCC funcSetset vs funcsetvector, i was reading the fico computation code.

Unless i'm missing something,  fico order as defined in the header file is precisely the output of the SCC algorithm if you didn't remove the singleton sccs because it's just a reverse topological ordering of the condensation graph.  

(at least for those things included in the scc finding).

I can totally buy that maybe the description in the header file is missing some details, etc, that make this wrong, hence this issue.

However, reading the current computation code, the ordering can *definitely* be found as an SCC finding pass over an induced graph (IE even if you have to augment the existing graph being walked with declarations or something). I can prove this to you formally if you like :)

Assuming i'm not crazy, once i finish up the cfg traversal patch, i'll  do a follow up that cleans up the SCC finder to be a little more generic and then uses it to compute the fico ordering.

**Comment by s3rvac** [comment]
Hi Daniel. I have looked into the code and I think you are right, i.e. `FuncInfoCompOrder` should be computable via reverse topological ordering of the condensation graph :+1:
