### ISSUE TITLE
Utilization of multiple cores

### ISSUE THREAD

**Issue by SamDecrock** [avast-tl/retdec#51]
Just wondering, is there a possibility to run retdec on multiple cores?

My decompilation process seems to be 'stuck' on `converting function_f8294()...` for several hours. I don't know if running the process on multiple cores would even help... or do I just need a faster CPU?

Thanks,
Sam

**Comment by s3rvac** [comment]
Hi. Currently, each tool in our toolchain is single threaded, so the number of cores you have is irrelevant. The only way to utilize more cores is to run several separate decompilations (of several different files).

> My decompilation process seems to be 'stuck' on converting function_f8294()... for several hours. I don't know if running the process on multiple cores would even help... or do I just need a faster CPU?

Please, open a new issue for this and attach the input binary file so we can investigate it. As a rule of thumb, if the decompilation does not finish within 10-30 minutes, I would suggest trying a different approach, e.g. decompiling only a part of the input file, as suggested [here](https://github.com/avast-tl/retdec/issues/13#issuecomment-352192225).

**Comment by SamDecrock** [comment]
Thanks for the quick reply!
