### ISSUE TITLE
Build of retdec-config fails with "undefined reference to Json::Value"

### ISSUE THREAD

**Issue by rchatsiri** [avast-tl/retdec#52]
I compile the Retdec source code. Error from compiling was showed an error as below.
```
[ 32%] Linking CXX executable retdec-config
../retdec-config/libretdec-config.a(architecture.cpp.o): In function `retdec_config::Architecture::getJsonValue() const':
architecture.cpp:(.text+0x4cd): undefined reference to `Json::Value::Value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
architecture.cpp:(.text+0x4da): undefined reference to `Json::Value::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
architecture.cpp:(.text+0x521): undefined reference to `Json::Value::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
architecture.cpp:(.text+0x5ce): undefined reference to `Json::Value::Value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
architecture.cpp:(.text+0x5db): undefined reference to `Json::Value::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
architecture.cpp:(.text+0x616): undefined reference to `Json::Value::Value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
architecture.cpp:(.text+0x623): undefined reference to `Json::Value::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
```
I check command line generate an error result again with ``` $make VERBOSE=1```. Error present as below.

```
cd /retdec/build/deps/fileformat/deps/retdec-config/src/retdec-configtool && cmake -E cmake_link_script CMakeFiles/retdec-configtool.dir/link.txt --verbose=1
/usr/local/bin/c++  -O3 -DNDEBUG   CMakeFiles/retdec-configtool.dir/retdec-configtool.cpp.o  -o retdec-config -Wl,-rpath,:::::::::::::: ../retdec-config/libretdec-config.a ../../../../../capstone2llvmir/deps/tl-cpputils/src/tl-cpputils/libtl-cpputils.a ../../../../../fnc-patterns/deps/fileformat/deps/retdec-config/deps/jsoncpp/jsoncpp-project-prefix/src/jsoncpp-project-build/src/lib_json/libjsoncpp.a /usr/local/lib64/libjsoncpp.a 
../retdec-config/libretdec-config.a(architecture.cpp.o): In function `retdec_config::Architecture::getJsonValue() const':
architecture.cpp:(.text+0x4cd): undefined reference to `Json::Value::Value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
```

Cross check library path of Jsoncpp library install in ``` /usr/local/lib64/ ``` completed.

**Comment by s3rvac** [comment]
Hi. Can you please provide the following details so we can investigate this further?
* What Linux distribution and version do you use?
* What CMake version do you use?
* What was the `cmake` command that you used before `make`?
* What compiler and version did you use for build?
* From what you have written, I assume that you have `jsoncpp` installed in your system. Correct?

**Comment by rchatsiri** [comment]
* Source code build on Linux-AWS-AMI
* Cmake version 3.10.1
*  Yes, I was run Cmake before use a Make command line.
* GCC version 5.3.0
* That path to install the Jsoncpp files are ``` /usr/local/lib64/ ```.  Path file contain library such as libjsoncpp.so.1.8.3 , libjsoncpp.so, libjsoncpp.so.a. Library and include files of the Jsoncpp compiled from source code.

**Comment by rchatsiri** [comment]
I think should close that issues because found the way to built step completed. The root cause ```$make -j4``` command line  instead of ```$make``` as manual suggested.

**Comment by s3rvac** [comment]
There is no need to close as `make -j4` is valid. From the output that you provided, it seems that jsoncpp is linked twice on your system when building `retdec-config`:
```
/usr/local/bin/c++ [..] retdec-configtool.cpp.o [..]
    jsoncpp/jsoncpp-project-prefix/[..]/lib_json/libjsoncpp.a /usr/local/lib64/libjsoncpp.a
```
First, there is our version, and then the system version, which should not be linked. What is strange is that I also have jsoncpp installed in my system, but it links fine (i.e. just once, our version).

We will investigate this.

**Comment by pro-spero** [comment]
I also run into these undefined references using on my Linux boxes.
One runs redhat, the other funtoo.
The build compilers are gcc 7.2. cmake is at version 3.10 (also tried with 3.9.3).
Build was attempted with simple 'make' after 'cmake' as well as 'cmake --build .'

**Comment by s3rvac** [comment]
@pro-spero Thank you for the confirmation. May I ask if you have JsonCpp installed in your system on these boxes? I am trying to reproduce this issue, but no success so far.

**Comment by pro-spero** [comment]
On the redhat machine the libraries are installed, but the headers are not present.
The funtoo machine has both headers and the binaries.

**Comment by pro-spero** [comment]
Piping the build outputs to a log file and checking the details I found that the dependent projects do not all use the same compiler (7.2) as the top level one, e.g., llvm itself selected the system compiler on redhat, which is 4.8.5. Such mixing will not work. I will attempt to get a more consistent use of compilers.

**Comment by s3rvac** [comment]
That's a good point. We will need to properly propagate the compiler selected in the top-level project to all the external projects (e.g. jsoncpp).

**Comment by pro-spero** [comment]
It is not sufficient to have the compiler in the path to be picked up, but setting the CC and CXX variables before calling the top level cmake for configuration apparently allows to avoid the problem of undefined references.

**Comment by s3rvac** [comment]
I have improved the build of `retdec-config` and `jsoncpp` so that they both use the same compiler. Could you please try to build the current `master` branch of the `retdec` repository (without any need to set any `CC` or `CXX` variables) to verify whether this fixed to build for you?

**Comment by pro-spero** [comment]
I can confirm that I can now build successfully without special settings to the environment. I successfully compiled the master branch at revision 74ae5a52da4a9d0fa7f313bceb8cdde2cafcd900.

**Comment by s3rvac** [comment]
Perfect, thank you for the confirmation! I am closing the issue, but if anyone still has these jsoncpp-related problems, let us know.
