### ISSUE TITLE
Building retdec failed on Windows 10 ("error C2039: 'string': is not a member of 'std'")

### ISSUE THREAD

**Issue by cycledetector** [avast-tl/retdec#520]
I was trying to build retdec on Windows 10 with the latest RC of Visual Studio, executing the following commands:

cmake .. -DCMAKE_INSTALL_PREFIX="C:\retdec" -G"Visual Studio 16 2019" -A"x64"
cmake --build . --config Release -- -m
 
and while it was building retdec-pat2yara, it threw the following error: `retdec\src\pat2yara/modifications.h(34): error C2039: 'string': is not a member of 'std'`

By including `<string>` in retdec\src\pat2yara/modifications.h the build completed successfully.

I wonder if that was a CMake configuration error since the aforementioned file (https://github.com/avast-tl/retdec/blob/master/src/pat2yara/modifications.h) has not been modified since Jun 10, 2018.

**Comment by s3rvac** [comment]
Thank you for the report! The include was indeed missing. I have added it in commit ebdecf19d949dbacf0391fb4f261dc13bc4881a7, so the build should now complete successfully.

**Comment by cycledetector** [comment]
Thank you for the quick feedback and the fix, building retdec-pat2yara completed succefully.
