### ISSUE TITLE
Integrate with Travis and a add badge

### ISSUE THREAD

**Issue by radare** [avast-tl/retdec#525]

**Comment by s3rvac** [comment]
Hi. Could you please elaborate? We have both integration with Travis CI ([link](https://travis-ci.org/avast-tl/retdec)) and badge in README:

[![Travis CI build status](https://travis-ci.org/avast-tl/retdec.svg?branch=master)](https://travis-ci.org/avast-tl/retdec)

**Comment by radare** [comment]
👓
