### ISSUE TITLE
How to generate a file that can be recompiled?

### ISSUE THREAD

**Issue by zaoqi** [avast-tl/retdec#529]
How to generate a file that can be recompiled?

**Comment by s3rvac** [comment]
Hi. As written in #45, producing recompilable C source code is not our main goal, so there is no special parameter that would magically make the output C code recompilable. Nevertheless, in some cases, the C source code that RetDec produces is recompilable, which we sometimes utilize in our tests (e.g. [this one](https://github.com/avast-tl/retdec-regression-tests/blob/master/integration/fpu/test.py), which checks that a program doing FPU computations is correctly decompiled, then recompiled, and produces correct output when run).

For more details, please see the discussion in #45.
