### ISSUE TITLE
Does retdec consider supporting other reverse engineering framework, such as radare2

### ISSUE THREAD

**Issue by wonderzdh** [avast-tl/retdec#532]
Does retdec consider supporting other reverse engineering framework, such as radare2

**Comment by PeterMatula** [comment]
We are exploring a possibility to use RetDec from radare2 and/or Cutter. I also think a x64dbg plugin would be possible. Both would be similar to our IDA plugin.

However, I'm not sure if this is what you are asking. Can you clarify what you mean by _supporting other reverse engineering framework_?

If you have some specific tool in mind, and there isn't already an issue asking for the support, feel free to create such an issue. It doesn't mean we will jump right into working on it, but it doesn't hurt to have it noted somewhere.

**Comment by wonderzdh** [comment]
Yes, when I used retdec-idaplugin, I found it to be much better than the decompiler on radare2(r2dec), even though it runs very slowly.
