### ISSUE TITLE
Build with VS 2017 fails when the 2015 toolset is not installed

### ISSUE THREAD

**Issue by s3rvac** [avast-tl/retdec#55]
Even though the README says that RetDec build should work with VS 2015 Update 2 or later, the build currently does not work with VS 2017 unless the 2015 toolset is installed (see e.g. #50, #61, https://github.com/avast-tl/fileformat/issues/4).

We are working on a fix. This is a tracking issue for all issues related to the build with VS 2017 without the 2015 toolset.

**Comment by metthal** [comment]
Fixed in 7ccf79f3efbae32200dc9a0ab65b5d1b7b3c5389
