### ISSUE TITLE
Build on Windows fails due to a path-limit error

### ISSUE THREAD

**Issue by I-MrFixIt-I** [avast-tl/retdec#61]
I currently don't have much time, so forgive me if there is not much detail.

I was able to successfully create the solution by following your description(s), but sadly I got some errors when building the project/solution in VS2017 (latest version).

Added the log, may you can see something.
[retdec build log.txt](https://github.com/avast-tl/retdec/files/1576922/retdec.build.log.txt)

My setup:
Win 10 Pro x64 (latest version)
VS2017 (latest version)

**Comment by stonedreamforest** [comment]
[similar issue here](https://github.com/avast-tl/retdec/issues/55)

**Comment by s3rvac** [comment]
Hi. Could you please provide also output from the following file(s) so we can investigate this further?
```
retdec/build/deps/fileformat/deps/retdec-config/deps/jsoncpp/jsoncpp-project-prefix/src/jsoncpp-project-stamp/jsoncpp-project-build-err.log
retdec/build/deps/fileformat/deps/retdec-config/deps/jsoncpp/jsoncpp-project-prefix/src/jsoncpp-project-stamp/jsoncpp-project-build-out.log
```

**Comment by I-MrFixIt-I** [comment]
So, I made a new clean build, this is the result (sry thats it's in german, do you need it in english? Can I change the language for msbuild output?)
[cmake log.txt](https://github.com/avast-tl/retdec/files/1580010/cmake.log.txt)
[msbuild retdec.sln log.txt](https://github.com/avast-tl/retdec/files/1580011/msbuild.retdec.sln.log.txt)
[msbuild INSTALL.vcxproj log.txt](https://github.com/avast-tl/retdec/files/1580012/msbuild.INSTALL.vcxproj.log.txt)

[jsoncpp-project-build-out.log](https://github.com/avast-tl/retdec/files/1580016/jsoncpp-project-build-out.log)

The jsoncpp-project-build-err log is empty.

**Comment by s3rvac** [comment]
Thank you for the outputs. German is alright I guess :-). In the outputs, I found the following two errors:

1:
```
error MSB3491: In die Datei
"jsoncpp_lib_static.dir\Release\jsoncpp_.2BEF112F.tlog\jsoncpp_lib_static.lastbuildstate"
konnten keine Zeilen geschrieben werden. Der angegebene Pfad und/oder Dateiname
ist zu lang. Der vollstandig qualifizierte Dateiname muss kurzer als 260
Zeichen und der Pfadname kurzer als 248 Zeichen sein.
[C:\Users\Kai\Documents\Programmierung\Gamehacking\retdec\build\deps\fileformat\deps\retdec-config\deps\jsoncpp\jsoncpp-project-prefix\src\jsoncpp-project-build\src\lib_json\jsoncpp_lib_static.vcxproj]
```
This says that the complete path to the file is too long (longer than 260 characters, which represents a limit on Windows). Could you please try to clone the repository into a shorter path (e.g. `C:\retdec`) and try the build again from there? If this turns out to be the reason why the build does not work for you, we will have to try to reduce the size of our build directory structure.

2:
```
89: #error:  "Unknown Visual Studio version."
[C:\Users\Kai\Documents\Programmierung\Gamehacking\retdec\build\deps\capstone2llvmir\deps\llvm\llvm-project-prefix\src\llvm-project-build\lib\DebugInfo\PDB\LLVMDebugInfoPDB.vcxproj]
[C:\Users\Kai\Documents\Programmierung\Gamehacking\retdec\build\deps\capstone2llvmir\deps\llvm\llvm-project.vcxproj]
```

This is a similar error that is reported [here](https://github.com/avast-tl/fileformat/issues/4#issuecomment-352960721). However, we were not able to reproduce it (see [this comment](https://github.com/avast-tl/fileformat/issues/4#issuecomment-353118356)). Maybe this is caused by the previous error. I would suggest you to try the build in a shorter path first (see above) and let us know.

**Comment by I-MrFixIt-I** [comment]
ah nice, I was able to fix it.
So, first I moved it to another folder (I just read that with Win10 we can disable this limit :), testing it now.).
I also had to make changes to all DIASession.cpp files (similar to https://github.com/avast-tl/fileformat/issues/4#issuecomment-352960721)
...\retdec\deps\llvm\src\lib\DebugInfo\PDB\DIA\DIASession.cpp
...\retdec\deps\fnc-patterns\deps\fileformat\deps\llvm\src\lib\DebugInfo\PDB\DIA\DIASession.cpp
...\retdec\deps\capstone2llvmir\deps\llvm\src\lib\DebugInfo\PDB\DIA\DIASession.cpp
...\retdec\deps\fileformat\deps\llvm\src\lib\DebugInfo\PDB\DIA\DIASession.cpp

I changed there
```
#if _MSC_VER >= 1910
  msdia_dll = L"msdia140.dll"; // VS2017
#elif _MSC_VER == 1900
  msdia_dll = L"msdia140.dll"; // VS2015
#elif _MSC_VER == 1800
  msdia_dll = L"msdia120.dll"; // VS2013
#else
#error "Unknown Visual Studio version."
#endif
```
to
```
#if _MSC_VER >= 1910
  msdia_dll = L"msdia140.dll"; // VS2017
#elif _MSC_VER == 1900
  msdia_dll = L"msdia140.dll"; // VS2015
#elif _MSC_VER == 1800
  msdia_dll = L"msdia120.dll"; // VS2013
#else
#error "Unknown Visual Studio version."
#endif
```

I simply took >= 1910 because my _MSC_VER was 1912

**Comment by s3rvac** [comment]
I am going to fix `DBASession.cpp` based on [this comment](https://github.com/avast-tl/fileformat/issues/4#issuecomment-353539868) and will let you know.

**Comment by s3rvac** [comment]
In [9ab4f56e3](https://github.com/avast-tl/llvm/commit/9ab4f56e33e9dfe3b7c1759f99d8b23baa161874), I have fixed the compilation of `DIASession.cpp` with VS 2017 when DIA SDK is installed, so the build should work now.

> EDIT: Well, the path limit fix does not work with msbuild

Please, can you elaborate? Did it fail with the same error as before or with a different one?

**Comment by I-MrFixIt-I** [comment]
> Please, can you elaborate? Did it fail with the same error as before or with a different one?

With exactly the same error. As far as I can see there is nothing you can do about it (except changing the directory structure). MSBuild needs to be "patched" which seems to be quite hard.
Due to the path limit I can't even load the project in Visual Studio, trying so throws the path error again.

**Comment by s3rvac** [comment]
This is strange as we are able to build it on Windows. Nevertheless, we will most definitely try to reduce the length and depth of the directory structure.

**Comment by I-MrFixIt-I** [comment]
`This is strange as we are able to build it on Windows. Nevertheless, we will most definitely try to reduce the length and depth of the directory structure.`

Just to clarify, I can also build the project(s), but just not from my normal path where my other projects are located. Building it from C:\retdec directly works just fine.

**Comment by s3rvac** [comment]
Ah, I see. OK. We will try to do something with the long paths that we create during the build.

**Comment by s3rvac** [comment]
In ecba1a6367773088ec98cb08190f37df381c6f51, I have reduced the length of paths created by external projects. In the case of `jsoncpp` (the offending library), the path lengths got decreased by 60 characters.

Would you be able to test the build of the current `master` branch in the original location (`C:\Users\Kai\Documents\Programmierung\Gamehacking\retdec`) to see whether this fixed the build for you?

**Comment by I-MrFixIt-I** [comment]
Works fine now, thx for the fast changes :)

**Comment by s3rvac** [comment]
Perfect, thanks for the verification!
