### ISSUE TITLE
Decompilation failed due to segmentation fault in "signed/unsigned types fixing"

### ISSUE THREAD

**Issue by Astyc84** [avast-tl/retdec#64]
Running phase: removing code that is not reachable in a CFG ( 1450.21s )
Warning: [NonRecursiveCFGBuilder] there is no node for an edge to `v5_4065bb = *(IntToPtrCastExpr<ptr>((v0_4065dd + 1)))` -> skipping this edge
Running phase: signed/unsigned types fixing ( 1463.72s )
decompile.sh: line 947: 14280 Segmentation fault      $LLVMIR2HLL "${LLVMIR2HLL_PARAMS[@]}"
Error: Decompilation of file 'C:/Users/User/Desktop/ips.c.backend.bc' failed

**Comment by s3rvac** [comment]
Thank you for the report. This problem has been already discussed in #47, so I am closing this issue as a duplicate. Let's continue in #47.

**Comment by govnodecompiler003** [comment]
This is nеw sаmplе with sourcе codе for tеst this issuе.

Code contain simple 'hello world' function.


**RеtDеc** dеcompilе this filе more than 10 hours аnd crаsh at 11 hour
**Snowmаn** decompile it in 5 minut with succеss rеsult


Sourcе codе:
https://github.com/avast/retdec/files/4205822/Source.zip
Executable(sample, x64):
https://github.com/avast/retdec/files/4205825/TestRetdec2.zip


**s4rvac**, Lеt's plаy thе gаmе "dеlеtе thе mеssаgе if you cаn"? I love games!
