### ISSUE TITLE
strange problem

### ISSUE THREAD

**Issue by darkgirl** [avast-tl/retdec#78]
i work on linux platform,
but when i build this project,there were a lot of strange problems cause by just line break.
when window text file using CRLF, it might cause some strange problem.

i hope we can use the same line break both in windows and linux and won't cause these problems.
thanks.

**Comment by s3rvac** [comment]
Hi. Could you please be more specific?
* What did you run?
* What happened? What did it print?
* What did you expect that would happen?

A lot of use Linux and we have not encountered any line-break-related problems.

**Comment by s3rvac** [comment]
I am closing this as we have not received the requested details (it has been a week). We do not have enough information to investigate this further. If you provide the missing details, feel free to reopen.
