### ISSUE TITLE
How to improve decompilation of executables containing code from custom libraries?

### ISSUE THREAD

**Issue by mohe2015** [avast-tl/retdec#79]
I would like it if there would be instructions somewhere, which tell you how to decompile custom libraries correctly. It would also be great if retdec would do that with the c++ standard library by default.

**Comment by s3rvac** [comment]
Hi. Could you please elaborate on what you mean by _how to decompile custom libraries correctly_? Is it any of the following options?
1. You have a statically linkable library (e.g. `.a` on Linux or `.lib` on Windows) and you would like to decompile all object files from this library?
2. You have a dynamically linked library (e.g. `.so` on Linux or `.dll` on Windows) and you would like to decompile this library?
3. You have an executable (e.g. ELF on Linux or `.exe` PE on Windows) that contains a statically linked library and you would all code from this library to be skipped when decompiling? For example, when the executable calls some function `foo()` from the library, you would like to skip decompilation of the body of `foo()` as it comes from the library?

**Comment by mohe2015** [comment]
@s3rvac I mean the third option.

**Comment by mbandzi** [comment]
Hello,

the most easy way to do this is to use option `--static-code-archive <path/to/lib.a>`. This takes the library, creates signatures and uses them in decompilation process. This argument can be used multiple times for as many libraries as you need.

If you will be using same libraries for multiple decompilations, you should use option `--static-code-sigfile <path/to/signatures.yara>`. You can get signature files by either using tool `signature-from-library.sh` or simply taking files with .yara suffix from output folder after using first option.

**Optional**: for even better performance, signatures can be compiled using tool **yarac**. However, version of **yarac** must match version currently used in decompiler, so do not use your system version if you have yara installed. You can use our yara fork (https://github.com/avast-tl/yara) or try to find yarac binary somewhere in the build directory (right now, it is not installed to install directory).

**Note**: creating signatures from huge libraries can take some time as one step has currently O(n^2) time complexity where n is number of functions in libraries.

**Comment by Rushikesh-Tanpure** [comment]
What for second option
