### ISSUE TITLE
black screen when decompiling HxD

### ISSUE THREAD

**Issue by MerovingianByte** [avast-tl/retdec#81]
The executable is not even that big, 1.6MB. I got a black screen, last value I saw was over 14GB memory used. You can get [HxD here](https://mh-nexus.de/en/hxd/). It failed on the phase right after simplecopypropagation.

**Comment by s3rvac** [comment]
Thank you for the report. This is the same issue as in #13 and #36. We have already a general tracking issue for high-memory requirements (#16), so I am closing this as a duplicate.

We will have to investigate the decompilation to see why it requires so much memory. For a workaround, see [this comment](https://github.com/avast-tl/retdec/issues/13#issuecomment-352192225).

**Comment by MerovingianByte** [comment]
Ok, I thought finding an executable with the problem that I could share would help. Issue #36 I closed myself because I couldn't share the executable.

**Comment by s3rvac** [comment]
When we get to that, we will analyze all the submitted binaries. Feel free to submit more if you encounter them, but preferably into an already opened issue, such as #13 or #36. We do not want to have many opened issues that are just duplicates of each other as this clutters the issue list.

**Comment by MerovingianByte** [comment]
Ok sure! I'll do that. Do you have an email I could use to contact you? This way I could tell you about some executables that can't be shared for investigation.

**Comment by s3rvac** [comment]
You can use the email that I use in commits in this repository.
