### ISSUE TITLE
Add support for running RetDec under WSL (Windows Subsystem for Linux) on Windows 10

### ISSUE THREAD

**Issue by s3rvac** [avast-tl/retdec#85]
At the moment, RetDec has to be run via MSYS2 as it does not work correctly under WSL (see e.g. #18 and a note on [our wiki](https://github.com/avast-tl/retdec/wiki/Windows-Environment)). For our Windows 10 users, it would be beneficial if RetDec also worked under WSL.

First, we will have to investigate what would it take to make RetDec runnable under WSL. We can start from [this tip](https://github.com/avast-tl/retdec/issues/18#issuecomment-356115163).

**Comment by PeterMatula** [comment]
Invalid after we moved from Bash to Python (#147, #338).
