### ISSUE TITLE
MacOS problem executing decompile

### ISSUE THREAD

**Issue by waldi** [avast-tl/retdec#91]
Hi,
I successfully compiled retdec on MacOS but i'm having troubles executing it.

Bash Version: 4.4

**./decompile.sh File.exe**
```
##### Checking if file is a Mach-O Universal static library...
RUN: /Users/name/bin/retdec/bin/macho-extractor --list /Users/name/bin/retdec/bin/File.exe

##### Checking if file is an archive...
RUN: /Users/name/bin/retdec/bin/ar-extractor --arch-magic /Users/name/bin/retdec/bin/File.exe
Not an archive, going to the next step.
./decompile.sh: line 995: unexpected EOF while looking for matching `"'
./decompile.sh: line 996: syntax error: unexpected end of file
```

**cat ~/.bashrc**
```
echo "Hello from .bashrc"

export PATH="/usr/local/opt/bison/bin:$PATH"
export PATH="/usr/local/opt/flex/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/bc/bin:$PATH"
export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"
```

Someone has any idea what i'm doing wrong?

**Comment by waldi** [comment]
Ok sorry I found the problem. 
The decompile.sh uses 

> #!/bin/bash

If you install the bash >= 4 with brew you should set the bash version in the decompile.sh to 

> #!/usr/local/bin/bash

**Comment by s3rvac** [comment]
You can also run the script directly via a proper version of Bash:
```
/usr/local/bin/bash $RETDEC_INSTALL_DIR/bin/decompile.sh test.exe
```
In this way, no modifications are needed. This is the suggested way in our [README](https://github.com/avast-tl/retdec#macos). You can even add an alias for that:
```
alias dec="/usr/local/bin/bash $RETDEC_INSTALL_DIR/bin/decompile.sh"
```
which allows you to run just
```
dec test.exe
```
from anywhere.
