### ISSUE TITLE
git pull error: The following untracked working tree files would be overwritten by merge

### ISSUE THREAD

**Issue by PeterMatula** [avast-tl/retdec#92]
Pulling a new master ends with the following error:
```
$ git pull
error: The following untracked working tree files would be overwritten by merge:
        deps/googletest/CMakeLists.txt
        deps/libdwarf/CMakeLists.txt
        deps/llvm/CMakeLists.txt
Please move or remove them before you can merge.
Aborting
```

**Comment by PeterMatula** [comment]
This is caused by changing the basic structure of the `retdec` repository. We got rid of all git submodules. See https://github.com/avast-tl/retdec/wiki/Project-Repository-Structure for more details.

The are two possible solutions:
1. Easy - remove old repository and clone a new one:
```
rm -rf retdec
git clone https://github.com/avast-tl/retdec.git
```
2. Harder - fix existing repository:
```
git submodule deinit --all
git pull
```

**Comment by PeterMatula** [comment]
This is not really an issue that could be solved. Everyone that had `retdec` cloned before the change will have to manually fix the repository according to the instructions above.

I will keep this open for now, since this way, it is more visible for anyone searching for the reason why `git pull` is not working.

**Comment by mtkumar82** [comment]
git fetch --all
git reset --hard origin/{{your branch name}}

This worked for me, May be helpful for other.

**Comment by muriminyaga** [comment]
Yes this works..thanks

**Comment by Shravankumarhiregoudar** [comment]
Even after performing the above steps my issue was not solved.
So, unfortunately, I created a new folder and cloned.

**Comment by vidven09** [comment]
take this example:
$ git pull
error: The following untracked working tree files would be overwritten by merge:
        deps/googletest/CMakeLists.txt
        deps/libdwarf/CMakeLists.txt
        deps/llvm/CMakeLists.txt
Please move or remove them before you can merge.
Aborting

What if I am OK to overwrite one file due to merge but want to retain my version for 2 other files?

**Comment by auxiliaryjoel** [comment]
I'm having this same problem, I tried:
`git stash`
`git stash drop`
`git pull origin master`
but it still results in the same warning:
error: The following untracked working tree files would be overwritten by merge:
	web/themes/contrib/bootstrap_barrio/css/components/progress.css
	web/themes/contrib/bootstrap_barrio/js/toast.js
	web/themes/contrib/bootstrap_barrio/scripts/create_subtheme.sh
	web/themes/contrib/bootstrap_barrio/templates/layout/maintenance-page.html.twig
Please move or remove them before you merge.
Aborting

How do I get around this?

**Comment by s3rvac** [comment]
@auxiliaryjoel I think that you are in the wrong project (we have never had any of the mentioned files in our repository). Are you sure that you are in a RetDec repository?

**Comment by auxiliaryjoel** [comment]
@s3rvac oh sorry for confusion I noticed the last person to comment on this was having the same problem (different files but the same problem). I was wondering if @vidven09 was able to resolve their issue. If they have, I think what worked for them may answer my issue?

**Comment by subhashreeradhakrishnan** [comment]
$ git add *
$ git stash
$ git pull origin tlt/{branch_name}

You will lose the local changes however.

**Comment by auxiliaryjoel** [comment]
oh ok so the :
$ git add *
I would do on the remote server that I'm intending to git pull to?

**Comment by alpizano** [comment]
> git fetch --all
> git reset --hard origin/{{your branch name}}
> 
> This worked for me, May be helpful for other.

omgthank you

**Comment by weberthmo** [comment]
run...
git add *
git pull origin master
git pull

**Comment by fisicaetcetera** [comment]
> $ git add *
> $ git stash
> $ git pull origin master/{branch_name}
> 
> You will lose the local changes however.
My change was on remote.  Worked fine.  Thanks!

**Comment by rlynch99** [comment]
ok.. nothing too tough about it.. i had one file listed.. I deleted it, then did a git pull,
all good.
(if you need too move the files to a different directory - not under git - and do the pull - you will always be able to move them back afterwards if needed.)

**Comment by s3rvac** [comment]
I am locking the issue as it has been solved and the newly appearing discussions are not related to RetDec.
