### ISSUE TITLE
Windows instructions are incomplete

### ISSUE THREAD

**Issue by Jasjar42** [avast-tl/retdec#99]
I'm trying to get retdec self hosting working on windows, but the windows instructions are incomplete. Setup (step 1-3) can be done. But step 4, where it tells you to type the command: "bash $RETDEC_INSTALL_DIR/bin/retdec-decompiler.sh test.exe", But that command just doesn't work,

That is because the provided binary(I'm using the AMD64 one) doesn't even have the file "retdec-decompiler.sh". Also, even if you get it manually, it still doesn't work since the binary doesn't contain the files it needs to run.

**Comment by s3rvac** [comment]
Hi. The Installation and Use instructions in our README currently correspond to the development version of the decompiler (`master` branch), where `decompile.sh` was renamed to `retdec-decompiler.sh`. If you use the latest stable version (3.0), you will need to run the following command instead:
```
bash $RETDEC_INSTALL_DIR/bin/decompile.sh test.exe
```
